-- =============================================
-- WEB3-BASICS QUIZ QUESTIONS
-- 15 questions per section × 8 sections = 120 total
-- =============================================

-- =============================================
-- SECTION 1: Evolution (15 questions)
-- =============================================
WITH s1 AS (SELECT id FROM course_sections WHERE slug = 'evolution' AND course_id = 'web3-basics' LIMIT 1)
INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
VALUES
((SELECT id FROM s1), '{"en": "What defines Web 1.0?", "es": "¿Qué define a Web 1.0?"}', '[{"en": "Read-only static pages", "es": "Páginas estáticas solo lectura"}, {"en": "Social media", "es": "Redes sociales"}, {"en": "Blockchain", "es": "Blockchain"}]', 0, '{"en": "Web 1.0 was read-only with no user interaction.", "es": "Web 1.0 era solo lectura sin interacción."}'),
((SELECT id FROM s1), '{"en": "What is the key feature of Web 2.0?", "es": "¿Cuál es la característica clave de Web 2.0?"}', '[{"en": "Decentralization", "es": "Descentralización"}, {"en": "User-generated content", "es": "Contenido generado por usuarios"}, {"en": "Blockchain", "es": "Blockchain"}]', 1, '{"en": "Web 2.0 enabled users to create content.", "es": "Web 2.0 permitió a usuarios crear contenido."}'),
((SELECT id FROM s1), '{"en": "What makes Web 3.0 different?", "es": "¿Qué hace diferente a Web 3.0?"}', '[{"en": "User ownership", "es": "Propiedad del usuario"}, {"en": "More ads", "es": "Más anuncios"}, {"en": "Faster loading", "es": "Carga más rápida"}]', 0, '{"en": "Web 3.0 gives users ownership of data and assets.", "es": "Web 3.0 da a usuarios propiedad de datos y activos."}'),
((SELECT id FROM s1), '{"en": "Who owns your data in Web 2.0?", "es": "¿Quién posee tus datos en Web 2.0?"}', '[{"en": "You", "es": "Tú"}, {"en": "Platforms like Facebook", "es": "Plataformas como Facebook"}, {"en": "Government", "es": "Gobierno"}]', 1, '{"en": "In Web 2.0, platforms own and monetize your data.", "es": "En Web 2.0, las plataformas poseen y monetizan tus datos."}'),
((SELECT id FROM s1), '{"en": "What is your identity in Web 3.0?", "es": "¿Cuál es tu identidad en Web 3.0?"}', '[{"en": "Your email", "es": "Tu email"}, {"en": "Your wallet address", "es": "Tu dirección de wallet"}, {"en": "Your phone number", "es": "Tu número de teléfono"}]', 1, '{"en": "Your crypto wallet is your Web3 identity.", "es": "Tu wallet es tu identidad Web3."}'),
((SELECT id FROM s1), '{"en": "What decade was Web 1.0?", "es": "¿En qué década fue Web 1.0?"}', '[{"en": "1990s", "es": "1990s"}, {"en": "2000s", "es": "2000s"}, {"en": "2010s", "es": "2010s"}]', 0, '{"en": "Web 1.0 was the internet of the 1990s.", "es": "Web 1.0 fue el internet de los 1990s."}'),
((SELECT id FROM s1), '{"en": "Can content be censored in Web 2.0?", "es": "¿Puede censurarse contenido en Web 2.0?"}', '[{"en": "Yes", "es": "Sí"}, {"en": "No", "es": "No"}, {"en": "Sometimes", "es": "A veces"}]', 0, '{"en": "Platforms can remove any content they want.", "es": "Las plataformas pueden eliminar cualquier contenido."}'),
((SELECT id FROM s1), '{"en": "What is censorship-resistant?", "es": "¿Qué es resistente a censura?"}', '[{"en": "Web 1.0", "es": "Web 1.0"}, {"en": "Web 2.0", "es": "Web 2.0"}, {"en": "Web 3.0", "es": "Web 3.0"}]', 2, '{"en": "Web 3.0 content stored on blockchain cannot be deleted.", "es": "Contenido Web 3.0 en blockchain no puede eliminarse."}'),
((SELECT id FROM s1), '{"en": "How do payments work in Web 3.0?", "es": "¿Cómo funcionan los pagos en Web 3.0?"}', '[{"en": "Through banks", "es": "A través de bancos"}, {"en": "Peer-to-peer", "es": "Peer-to-peer"}, {"en": "Cash only", "es": "Solo efectivo"}]', 1, '{"en": "Web 3.0 enables direct peer-to-peer payments.", "es": "Web 3.0 permite pagos directos peer-to-peer."}'),
((SELECT id FROM s1), '{"en": "Which is an example of Web 2.0 login?", "es": "¿Cuál es ejemplo de login Web 2.0?"}', '[{"en": "MetaMask", "es": "MetaMask"}, {"en": "Login with Google", "es": "Login con Google"}, {"en": "Ledger", "es": "Ledger"}]', 1, '{"en": "Login with Google gives them access to your data.", "es": "Login con Google les da acceso a tus datos."}'),
((SELECT id FROM s1), '{"en": "What is a key problem with Web 2.0?", "es": "¿Cuál es un problema clave de Web 2.0?"}', '[{"en": "Too slow", "es": "Muy lento"}, {"en": "Data breaches and privacy", "es": "Filtraciones y privacidad"}, {"en": "Too expensive", "es": "Muy caro"}]', 1, '{"en": "Centralized data = single point of failure.", "es": "Datos centralizados = punto único de fallo."}'),
((SELECT id FROM s1), '{"en": "What can you own in Web 3.0?", "es": "¿Qué puedes poseer en Web 3.0?"}', '[{"en": "Only money", "es": "Solo dinero"}, {"en": "Data, money, and digital assets", "es": "Datos, dinero y activos digitales"}, {"en": "Nothing", "es": "Nada"}]', 1, '{"en": "Web 3.0 enables ownership of all digital assets.", "es": "Web 3.0 permite propiedad de todos los activos digitales."}'),
((SELECT id FROM s1), '{"en": "Who controls Web 3.0?", "es": "¿Quién controla Web 3.0?"}', '[{"en": "Google", "es": "Google"}, {"en": "Governments", "es": "Gobiernos"}, {"en": "Users collectively", "es": "Usuarios colectivamente"}]', 2, '{"en": "Web 3.0 is decentralized, controlled by users.", "es": "Web 3.0 es descentralizado, controlado por usuarios."}'),
((SELECT id FROM s1), '{"en": "What enables Web 3.0 to work?", "es": "¿Qué permite que Web 3.0 funcione?"}', '[{"en": "Faster servers", "es": "Servidores más rápidos"}, {"en": "Blockchain technology", "es": "Tecnología blockchain"}, {"en": "More data centers", "es": "Más centros de datos"}]', 1, '{"en": "Blockchain is the foundational technology of Web 3.0.", "es": "Blockchain es la tecnología fundamental de Web 3.0."}'),
((SELECT id FROM s1), '{"en": "What is the main promise of Web 3.0?", "es": "¿Cuál es la promesa principal de Web 3.0?"}', '[{"en": "Faster internet", "es": "Internet más rápido"}, {"en": "User sovereignty", "es": "Soberanía del usuario"}, {"en": "Free content", "es": "Contenido gratis"}]', 1, '{"en": "Web 3.0 promises users control over their digital lives.", "es": "Web 3.0 promete a usuarios control de sus vidas digitales."}');

-- =============================================
-- SECTION 2: Blockchain (15 questions)
-- =============================================
WITH s2 AS (SELECT id FROM course_sections WHERE slug = 'blockchain' AND course_id = 'web3-basics' LIMIT 1)
INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
VALUES
((SELECT id FROM s2), '{"en": "What is a blockchain?", "es": "¿Qué es blockchain?"}', '[{"en": "A type of bank", "es": "Un tipo de banco"}, {"en": "A distributed ledger", "es": "Un libro mayor distribuido"}, {"en": "A social network", "es": "Una red social"}]', 1, '{"en": "Blockchain is a distributed ledger shared across many computers.", "es": "Blockchain es un libro mayor distribuido entre muchas computadoras."}'),
((SELECT id FROM s2), '{"en": "Can blockchain data be modified?", "es": "¿Pueden modificarse datos en blockchain?"}', '[{"en": "Yes, easily", "es": "Sí, fácilmente"}, {"en": "No, it is immutable", "es": "No, es inmutable"}, {"en": "Only by admins", "es": "Solo por admins"}]', 1, '{"en": "Once written, blockchain data cannot be changed.", "es": "Una vez escrito, los datos de blockchain no pueden cambiarse."}'),
((SELECT id FROM s2), '{"en": "What are blocks in blockchain?", "es": "¿Qué son los bloques en blockchain?"}', '[{"en": "Physical storage units", "es": "Unidades de almacenamiento físicas"}, {"en": "Containers of transaction data", "es": "Contenedores de datos de transacciones"}, {"en": "Mining equipment", "es": "Equipo de minería"}]', 1, '{"en": "Blocks contain transaction data with timestamps.", "es": "Los bloques contienen datos de transacciones con timestamps."}'),
((SELECT id FROM s2), '{"en": "What links blocks together?", "es": "¿Qué une los bloques?"}', '[{"en": "Cables", "es": "Cables"}, {"en": "Cryptographic hashes", "es": "Hashes criptográficos"}, {"en": "Passwords", "es": "Contraseñas"}]', 1, '{"en": "Each block contains the hash of the previous block.", "es": "Cada bloque contiene el hash del bloque anterior."}'),
((SELECT id FROM s2), '{"en": "What is a node?", "es": "¿Qué es un nodo?"}', '[{"en": "A cryptocurrency", "es": "Una criptomoneda"}, {"en": "A computer in the network", "es": "Una computadora en la red"}, {"en": "A type of wallet", "es": "Un tipo de billetera"}]', 1, '{"en": "Nodes are computers that validate and store blockchain data.", "es": "Los nodos son computadoras que validan y almacenan datos."}'),
((SELECT id FROM s2), '{"en": "What is consensus?", "es": "¿Qué es consenso?"}', '[{"en": "Agreement among nodes", "es": "Acuerdo entre nodos"}, {"en": "A type of crypto", "es": "Un tipo de crypto"}, {"en": "A wallet feature", "es": "Una función de wallet"}]', 0, '{"en": "Consensus is how nodes agree on the state of the blockchain.", "es": "Consenso es cómo los nodos acuerdan el estado de la blockchain."}'),
((SELECT id FROM s2), '{"en": "Advantage of blockchain vs banks?", "es": "¿Ventaja de blockchain vs bancos?"}', '[{"en": "Slower", "es": "Más lento"}, {"en": "Available 24/7", "es": "Disponible 24/7"}, {"en": "More paperwork", "es": "Más papeleo"}]', 1, '{"en": "Blockchain works 24/7 without bank hours or holidays.", "es": "Blockchain funciona 24/7 sin horarios ni feriados."}'),
((SELECT id FROM s2), '{"en": "Who verifies blockchain transactions?", "es": "¿Quién verifica transacciones blockchain?"}', '[{"en": "Banks", "es": "Bancos"}, {"en": "Network nodes", "es": "Nodos de la red"}, {"en": "Government", "es": "Gobierno"}]', 1, '{"en": "Thousands of nodes verify each transaction.", "es": "Miles de nodos verifican cada transacción."}'),
((SELECT id FROM s2), '{"en": "What is transparency in blockchain?", "es": "¿Qué es transparencia en blockchain?"}', '[{"en": "Hidden data", "es": "Datos ocultos"}, {"en": "Anyone can see transactions", "es": "Cualquiera puede ver transacciones"}, {"en": "Private only", "es": "Solo privado"}]', 1, '{"en": "All transactions are publicly visible on the blockchain.", "es": "Todas las transacciones son públicamente visibles."}'),
((SELECT id FROM s2), '{"en": "What is decentralization?", "es": "¿Qué es descentralización?"}', '[{"en": "One central server", "es": "Un servidor central"}, {"en": "No single point of control", "es": "Ningún punto único de control"}, {"en": "Government control", "es": "Control gubernamental"}]', 1, '{"en": "Decentralization means no single entity controls the system.", "es": "Descentralización significa que ninguna entidad controla el sistema."}'),
((SELECT id FROM s2), '{"en": "What is PoW?", "es": "¿Qué es PoW?"}', '[{"en": "Proof of Work", "es": "Prueba de Trabajo"}, {"en": "Power of Wallet", "es": "Poder de Wallet"}, {"en": "Protocol of Web", "es": "Protocolo de Web"}]', 0, '{"en": "Proof of Work is a consensus mechanism using computing power.", "es": "Proof of Work es un mecanismo de consenso usando poder de cómputo."}'),
((SELECT id FROM s2), '{"en": "What is PoS?", "es": "¿Qué es PoS?"}', '[{"en": "Point of Sale", "es": "Punto de Venta"}, {"en": "Proof of Stake", "es": "Prueba de Participación"}, {"en": "Proof of Storage", "es": "Prueba de Almacenamiento"}]', 1, '{"en": "Proof of Stake uses staked tokens instead of computing power.", "es": "Proof of Stake usa tokens apostados en vez de poder de cómputo."}'),
((SELECT id FROM s2), '{"en": "Why is blockchain secure?", "es": "¿Por qué blockchain es seguro?"}', '[{"en": "Strong passwords", "es": "Contraseñas fuertes"}, {"en": "Cryptographic linking", "es": "Enlace criptográfico"}, {"en": "Firewalls", "es": "Firewalls"}]', 1, '{"en": "Changing one block would invalidate all subsequent blocks.", "es": "Cambiar un bloque invalidaría todos los bloques posteriores."}'),
((SELECT id FROM s2), '{"en": "What is a hash?", "es": "¿Qué es un hash?"}', '[{"en": "A password", "es": "Una contraseña"}, {"en": "A unique digital fingerprint", "es": "Una huella digital única"}, {"en": "A wallet address", "es": "Una dirección de wallet"}]', 1, '{"en": "Hashes uniquely identify data and detect any changes.", "es": "Los hashes identifican datos únicamente y detectan cambios."}'),
((SELECT id FROM s2), '{"en": "Is blockchain borderless?", "es": "¿Es blockchain sin fronteras?"}', '[{"en": "No, country-specific", "es": "No, específico por país"}, {"en": "Yes, works globally", "es": "Sí, funciona globalmente"}, {"en": "Only in USA", "es": "Solo en EE.UU."}]', 1, '{"en": "Blockchain works the same everywhere in the world.", "es": "Blockchain funciona igual en todo el mundo."}');

-- =============================================
-- SECTION 3: Applications (15 questions)
-- =============================================
WITH s3 AS (SELECT id FROM course_sections WHERE slug = 'applications' AND course_id = 'web3-basics' LIMIT 1)
INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
VALUES
((SELECT id FROM s3), '{"en": "What is DeFi?", "es": "¿Qué es DeFi?"}', '[{"en": "Decentralized Finance", "es": "Finanzas Descentralizadas"}, {"en": "Digital Finance", "es": "Finanzas Digitales"}, {"en": "Default Finance", "es": "Finanzas Predeterminadas"}]', 0, '{"en": "DeFi = Decentralized Finance, financial services without banks.", "es": "DeFi = Finanzas Descentralizadas, servicios financieros sin bancos."}'),
((SELECT id FROM s3), '{"en": "What is an NFT?", "es": "¿Qué es un NFT?"}', '[{"en": "New Financial Token", "es": "Nuevo Token Financiero"}, {"en": "Non-Fungible Token", "es": "Token No Fungible"}, {"en": "Network File Transfer", "es": "Transferencia de Archivo de Red"}]', 1, '{"en": "NFT = Non-Fungible Token, a unique digital certificate.", "es": "NFT = Token No Fungible, un certificado digital único."}'),
((SELECT id FROM s3), '{"en": "What is a DEX?", "es": "¿Qué es un DEX?"}', '[{"en": "Decentralized Exchange", "es": "Exchange Descentralizado"}, {"en": "Digital Exchange", "es": "Exchange Digital"}, {"en": "Default Exchange", "es": "Exchange Predeterminado"}]', 0, '{"en": "DEX = Decentralized Exchange, trade without intermediaries.", "es": "DEX = Exchange Descentralizado, intercambia sin intermediarios."}'),
((SELECT id FROM s3), '{"en": "What are stablecoins?", "es": "¿Qué son stablecoins?"}', '[{"en": "Volatile crypto", "es": "Crypto volátil"}, {"en": "Crypto pegged to USD", "es": "Crypto vinculado al USD"}, {"en": "Mining rewards", "es": "Recompensas de minería"}]', 1, '{"en": "Stablecoins maintain stable value, usually pegged to $1.", "es": "Las stablecoins mantienen valor estable, usualmente $1."}'),
((SELECT id FROM s3), '{"en": "What is yield farming?", "es": "¿Qué es yield farming?"}', '[{"en": "Growing vegetables", "es": "Cultivar vegetales"}, {"en": "Earning rewards for providing liquidity", "es": "Ganar recompensas por proveer liquidez"}, {"en": "Mining Bitcoin", "es": "Minar Bitcoin"}]', 1, '{"en": "Provide liquidity to DeFi protocols, earn rewards.", "es": "Provee liquidez a protocolos DeFi, gana recompensas."}'),
((SELECT id FROM s3), '{"en": "What can NFTs represent?", "es": "¿Qué pueden representar los NFTs?"}', '[{"en": "Only art", "es": "Solo arte"}, {"en": "Art, music, tickets, and more", "es": "Arte, música, tickets y más"}, {"en": "Only gaming items", "es": "Solo items de juegos"}]', 1, '{"en": "NFTs can represent any unique digital or physical asset.", "es": "Los NFTs pueden representar cualquier activo único."}'),
((SELECT id FROM s3), '{"en": "How do artists benefit from NFTs?", "es": "¿Cómo benefician los NFTs a artistas?"}', '[{"en": "Free advertising", "es": "Publicidad gratis"}, {"en": "Automatic royalties on resales", "es": "Regalías automáticas en reventas"}, {"en": "More followers", "es": "Más seguidores"}]', 1, '{"en": "Artists receive royalties every time their NFT is resold.", "es": "Artistas reciben regalías cada vez que se revende su NFT."}'),
((SELECT id FROM s3), '{"en": "What is DeFi lending?", "es": "¿Qué son préstamos DeFi?"}', '[{"en": "Bank loans", "es": "Préstamos bancarios"}, {"en": "Lending crypto for interest", "es": "Prestar crypto por interés"}, {"en": "Credit cards", "es": "Tarjetas de crédito"}]', 1, '{"en": "Lend your crypto to earn interest, no banks involved.", "es": "Presta tu crypto para ganar interés, sin bancos."}'),
((SELECT id FROM s3), '{"en": "Who can access DeFi?", "es": "¿Quién puede acceder a DeFi?"}', '[{"en": "Only rich people", "es": "Solo gente rica"}, {"en": "Anyone with internet", "es": "Cualquiera con internet"}, {"en": "Only banks", "es": "Solo bancos"}]', 1, '{"en": "DeFi is permissionless, anyone can participate.", "es": "DeFi no tiene permisos, cualquiera puede participar."}'),
((SELECT id FROM s3), '{"en": "What is a DAO?", "es": "¿Qué es una DAO?"}', '[{"en": "Decentralized Autonomous Organization", "es": "Organización Autónoma Descentralizada"}, {"en": "Digital Art Organization", "es": "Organización de Arte Digital"}, {"en": "Data Access Object", "es": "Objeto de Acceso a Datos"}]', 0, '{"en": "DAOs are community-owned organizations governed by code.", "es": "Las DAOs son organizaciones comunitarias gobernadas por código."}'),
((SELECT id FROM s3), '{"en": "What is gas in Ethereum?", "es": "¿Qué es gas en Ethereum?"}', '[{"en": "Fuel for cars", "es": "Combustible para autos"}, {"en": "Transaction fees", "es": "Tarifas de transacción"}, {"en": "Mining power", "es": "Poder de minería"}]', 1, '{"en": "Gas is the fee paid to execute transactions on Ethereum.", "es": "Gas es la tarifa para ejecutar transacciones en Ethereum."}'),
((SELECT id FROM s3), '{"en": "What is a liquidity pool?", "es": "¿Qué es un pool de liquidez?"}', '[{"en": "A swimming pool", "es": "Una piscina"}, {"en": "Funds locked for trading", "es": "Fondos bloqueados para trading"}, {"en": "A bank account", "es": "Una cuenta bancaria"}]', 1, '{"en": "Liquidity pools enable decentralized trading.", "es": "Los pools de liquidez permiten trading descentralizado."}'),
((SELECT id FROM s3), '{"en": "What is airdrop in crypto?", "es": "¿Qué es airdrop en crypto?"}', '[{"en": "Parachute delivery", "es": "Entrega en paracaídas"}, {"en": "Free token distribution", "es": "Distribución gratuita de tokens"}, {"en": "Dropping prices", "es": "Caída de precios"}]', 1, '{"en": "Airdrops give free tokens to wallet addresses.", "es": "Los airdrops dan tokens gratis a direcciones de wallet."}'),
((SELECT id FROM s3), '{"en": "What is minting an NFT?", "es": "¿Qué es mintear un NFT?"}', '[{"en": "Deleting it", "es": "Eliminarlo"}, {"en": "Creating it on blockchain", "es": "Crearlo en blockchain"}, {"en": "Selling it", "es": "Venderlo"}]', 1, '{"en": "Minting creates a new NFT on the blockchain.", "es": "Mintear crea un nuevo NFT en la blockchain."}'),
((SELECT id FROM s3), '{"en": "What is a smart contract?", "es": "¿Qué es un contrato inteligente?"}', '[{"en": "A legal document", "es": "Un documento legal"}, {"en": "Self-executing code", "es": "Código auto-ejecutable"}, {"en": "A clever agreement", "es": "Un acuerdo inteligente"}]', 1, '{"en": "Smart contracts execute automatically when conditions are met.", "es": "Los contratos inteligentes se ejecutan automáticamente."}');

-- =============================================
-- SECTION 4: History (15 questions)
-- =============================================
WITH s4 AS (SELECT id FROM course_sections WHERE slug = 'history' AND course_id = 'web3-basics' LIMIT 1)
INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
VALUES
((SELECT id FROM s4), '{"en": "When was the Bitcoin whitepaper published?", "es": "¿Cuándo se publicó el whitepaper de Bitcoin?"}', '[{"en": "2008", "es": "2008"}, {"en": "2010", "es": "2010"}, {"en": "2015", "es": "2015"}]', 0, '{"en": "Satoshi Nakamoto published it in October 2008.", "es": "Satoshi Nakamoto lo publicó en octubre 2008."}'),
((SELECT id FROM s4), '{"en": "Who created Bitcoin?", "es": "¿Quién creó Bitcoin?"}', '[{"en": "Elon Musk", "es": "Elon Musk"}, {"en": "Satoshi Nakamoto", "es": "Satoshi Nakamoto"}, {"en": "Vitalik Buterin", "es": "Vitalik Buterin"}]', 1, '{"en": "Satoshi Nakamoto is the pseudonymous creator of Bitcoin.", "es": "Satoshi Nakamoto es el creador seudónimo de Bitcoin."}'),
((SELECT id FROM s4), '{"en": "When did Ethereum launch?", "es": "¿Cuándo se lanzó Ethereum?"}', '[{"en": "2012", "es": "2012"}, {"en": "2015", "es": "2015"}, {"en": "2018", "es": "2018"}]', 1, '{"en": "Ethereum launched in July 2015.", "es": "Ethereum se lanzó en julio 2015."}'),
((SELECT id FROM s4), '{"en": "What happened in DeFi Summer 2020?", "es": "¿Qué pasó en el verano DeFi 2020?"}', '[{"en": "Bitcoin crashed", "es": "Bitcoin cayó"}, {"en": "DeFi protocols exploded", "es": "Protocolos DeFi explotaron"}, {"en": "Crypto was banned", "es": "Crypto fue prohibido"}]', 1, '{"en": "DeFi protocols saw massive growth and adoption.", "es": "Los protocolos DeFi vieron crecimiento masivo."}'),
((SELECT id FROM s4), '{"en": "When did NFTs go mainstream?", "es": "¿Cuándo se popularizaron los NFTs?"}', '[{"en": "2019", "es": "2019"}, {"en": "2021", "es": "2021"}, {"en": "2023", "es": "2023"}]', 1, '{"en": "2021 saw NFT sales explode with Beeple and others.", "es": "2021 vio las ventas de NFT explotar."}'),
((SELECT id FROM s4), '{"en": "What did Ethereum introduce?", "es": "¿Qué introdujo Ethereum?"}', '[{"en": "Digital gold", "es": "Oro digital"}, {"en": "Smart contracts", "es": "Contratos inteligentes"}, {"en": "Faster payments", "es": "Pagos más rápidos"}]', 1, '{"en": "Ethereum enabled programmable smart contracts.", "es": "Ethereum habilitó contratos inteligentes programables."}'),
((SELECT id FROM s4), '{"en": "What was the ICO boom?", "es": "¿Qué fue el boom de ICOs?"}', '[{"en": "Initial Coin Offerings explosion in 2017", "es": "Explosión de Ofertas Iniciales de Moneda en 2017"}, {"en": "A crypto crash", "es": "Una caída de crypto"}, {"en": "A new coin", "es": "Una nueva moneda"}]', 0, '{"en": "2017 saw thousands of new tokens launched via ICOs.", "es": "2017 vio miles de nuevos tokens lanzados vía ICOs."}'),
((SELECT id FROM s4), '{"en": "Who created Ethereum?", "es": "¿Quién creó Ethereum?"}', '[{"en": "Satoshi Nakamoto", "es": "Satoshi Nakamoto"}, {"en": "Vitalik Buterin", "es": "Vitalik Buterin"}, {"en": "Charlie Lee", "es": "Charlie Lee"}]', 1, '{"en": "Vitalik Buterin proposed Ethereum in 2013.", "es": "Vitalik Buterin propuso Ethereum en 2013."}'),
((SELECT id FROM s4), '{"en": "How much did Beeple NFT sell for?", "es": "¿Por cuánto se vendió el NFT de Beeple?"}', '[{"en": "$6.9 million", "es": "$6.9 millones"}, {"en": "$69 million", "es": "$69 millones"}, {"en": "$690 million", "es": "$690 millones"}]', 1, '{"en": "Beeple sold Everydays for $69 million at Christie.", "es": "Beeple vendió Everydays por $69 millones en Christie."}'),
((SELECT id FROM s4), '{"en": "What is institutional adoption?", "es": "¿Qué es adopción institucional?"}', '[{"en": "Schools using crypto", "es": "Escuelas usando crypto"}, {"en": "Banks and corporations entering crypto", "es": "Bancos y corporaciones entrando a crypto"}, {"en": "Government ban", "es": "Prohibición gubernamental"}]', 1, '{"en": "Large financial institutions investing in crypto.", "es": "Grandes instituciones financieras invirtiendo en crypto."}'),
((SELECT id FROM s4), '{"en": "What is tokenization?", "es": "¿Qué es tokenización?"}', '[{"en": "Creating game tokens", "es": "Crear tokens de juego"}, {"en": "Representing real assets as tokens", "es": "Representar activos reales como tokens"}, {"en": "Breaking tokens", "es": "Romper tokens"}]', 1, '{"en": "Real estate, stocks, and art can become blockchain tokens.", "es": "Inmuebles, acciones y arte pueden ser tokens blockchain."}'),
((SELECT id FROM s4), '{"en": "What are L2 solutions?", "es": "¿Qué son soluciones L2?"}', '[{"en": "New blockchains", "es": "Nuevas blockchains"}, {"en": "Scaling solutions on top of L1", "es": "Soluciones de escalado sobre L1"}, {"en": "Mining hardware", "es": "Hardware de minería"}]', 1, '{"en": "Layer 2 solutions make transactions faster and cheaper.", "es": "Soluciones Layer 2 hacen transacciones más rápidas y baratas."}'),
((SELECT id FROM s4), '{"en": "When was the first Bitcoin block mined?", "es": "¿Cuándo se minó el primer bloque de Bitcoin?"}', '[{"en": "January 2008", "es": "Enero 2008"}, {"en": "January 2009", "es": "Enero 2009"}, {"en": "January 2010", "es": "Enero 2010"}]', 1, '{"en": "The genesis block was mined January 3, 2009.", "es": "El bloque génesis se minó el 3 de enero de 2009."}'),
((SELECT id FROM s4), '{"en": "What is crypto regulation?", "es": "¿Qué es regulación crypto?"}', '[{"en": "Government rules for crypto", "es": "Reglas gubernamentales para crypto"}, {"en": "Crypto controlling government", "es": "Crypto controlando gobierno"}, {"en": "No rules", "es": "Sin reglas"}]', 0, '{"en": "Governments are creating legal frameworks for crypto.", "es": "Los gobiernos están creando marcos legales para crypto."}'),
((SELECT id FROM s4), '{"en": "Where is Web3 heading?", "es": "¿Hacia dónde va Web3?"}', '[{"en": "Dying out", "es": "Muriendo"}, {"en": "Mass adoption", "es": "Adopción masiva"}, {"en": "Staying niche", "es": "Permaneciendo nicho"}]', 1, '{"en": "Experts predict Web3 will reach billions of users.", "es": "Expertos predicen que Web3 alcanzará billones de usuarios."}');

-- =============================================
-- SECTION 5: Use Cases (15 questions)
-- =============================================
WITH s5 AS (SELECT id FROM course_sections WHERE slug = 'use-cases' AND course_id = 'web3-basics' LIMIT 1)
INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
VALUES
((SELECT id FROM s5), '{"en": "How can blockchain help voting?", "es": "¿Cómo puede blockchain ayudar a votaciones?"}', '[{"en": "Faster counting", "es": "Conteo más rápido"}, {"en": "Tamper-proof records", "es": "Registros a prueba de manipulación"}, {"en": "More candidates", "es": "Más candidatos"}]', 1, '{"en": "Blockchain creates transparent, immutable voting records.", "es": "Blockchain crea registros de votación transparentes e inmutables."}'),
((SELECT id FROM s5), '{"en": "What is supply chain tracking?", "es": "¿Qué es rastreo de cadena de suministro?"}', '[{"en": "Tracking delivery trucks", "es": "Rastrear camiones"}, {"en": "Tracking products from origin to consumer", "es": "Rastrear productos de origen a consumidor"}, {"en": "Ordering supplies", "es": "Ordenar suministros"}]', 1, '{"en": "Verify where products came from and their journey.", "es": "Verificar de dónde vienen los productos y su recorrido."}'),
((SELECT id FROM s5), '{"en": "What is digital identity on blockchain?", "es": "¿Qué es identidad digital en blockchain?"}', '[{"en": "Your email address", "es": "Tu dirección de email"}, {"en": "Self-sovereign identity you control", "es": "Identidad auto-soberana que tú controlas"}, {"en": "Government ID", "es": "ID gubernamental"}]', 1, '{"en": "Own your identity without relying on big tech.", "es": "Poseer tu identidad sin depender de big tech."}'),
((SELECT id FROM s5), '{"en": "Which company uses blockchain for food safety?", "es": "¿Qué empresa usa blockchain para seguridad alimentaria?"}', '[{"en": "Amazon", "es": "Amazon"}, {"en": "Walmart", "es": "Walmart"}, {"en": "Netflix", "es": "Netflix"}]', 1, '{"en": "Walmart tracks food products using blockchain.", "es": "Walmart rastrea productos alimenticios usando blockchain."}'),
((SELECT id FROM s5), '{"en": "How can blockchain help healthcare?", "es": "¿Cómo puede blockchain ayudar en salud?"}', '[{"en": "Cheaper medicine", "es": "Medicina más barata"}, {"en": "Portable medical records", "es": "Registros médicos portables"}, {"en": "More doctors", "es": "Más doctores"}]', 1, '{"en": "Your medical records travel with you securely.", "es": "Tus registros médicos viajan contigo de forma segura."}'),
((SELECT id FROM s5), '{"en": "What problem does supply chain tracking solve?", "es": "¿Qué problema resuelve el rastreo de cadena de suministro?"}', '[{"en": "Slow shipping", "es": "Envío lento"}, {"en": "Counterfeit products", "es": "Productos falsificados"}, {"en": "High prices", "es": "Precios altos"}]', 1, '{"en": "Blockchain verifies product authenticity.", "es": "Blockchain verifica autenticidad de productos."}'),
((SELECT id FROM s5), '{"en": "What is verifiable credentials?", "es": "¿Qué son credenciales verificables?"}', '[{"en": "Digital diplomas and certificates", "es": "Diplomas y certificados digitales"}, {"en": "Passwords", "es": "Contraseñas"}, {"en": "Credit scores", "es": "Puntajes de crédito"}]', 0, '{"en": "Prove your credentials without revealing all your data.", "es": "Prueba tus credenciales sin revelar todos tus datos."}'),
((SELECT id FROM s5), '{"en": "How does blockchain help charities?", "es": "¿Cómo ayuda blockchain a organizaciones benéficas?"}', '[{"en": "More donors", "es": "Más donantes"}, {"en": "Transparent fund tracking", "es": "Rastreo transparente de fondos"}, {"en": "Tax benefits", "es": "Beneficios fiscales"}]', 1, '{"en": "Donors can track exactly where their money goes.", "es": "Donantes pueden rastrear exactamente a dónde va su dinero."}'),
((SELECT id FROM s5), '{"en": "What is a real estate use case?", "es": "¿Cuál es un caso de uso en bienes raíces?"}', '[{"en": "Faster construction", "es": "Construcción más rápida"}, {"en": "Tokenized property ownership", "es": "Propiedad tokenizada"}, {"en": "Cheaper rent", "es": "Alquiler más barato"}]', 1, '{"en": "Buy fractional ownership of real estate via tokens.", "es": "Compra propiedad fraccionada de inmuebles vía tokens."}'),
((SELECT id FROM s5), '{"en": "How can blockchain help music artists?", "es": "¿Cómo puede blockchain ayudar a artistas musicales?"}', '[{"en": "More concerts", "es": "Más conciertos"}, {"en": "Direct royalty payments", "es": "Pagos de regalías directos"}, {"en": "Better sound quality", "es": "Mejor calidad de sonido"}]', 1, '{"en": "Artists receive royalties directly without labels.", "es": "Artistas reciben regalías directamente sin sellos."}'),
((SELECT id FROM s5), '{"en": "What is gaming use case for blockchain?", "es": "¿Cuál es un caso de uso en gaming?"}', '[{"en": "Better graphics", "es": "Mejores gráficos"}, {"en": "True ownership of in-game items", "es": "Propiedad real de items del juego"}, {"en": "Faster loading", "es": "Carga más rápida"}]', 1, '{"en": "Own and trade game items across platforms.", "es": "Posee y comercia items de juegos entre plataformas."}'),
((SELECT id FROM s5), '{"en": "How can blockchain prevent diploma fraud?", "es": "¿Cómo puede blockchain prevenir fraude de diplomas?"}', '[{"en": "Digital signatures", "es": "Firmas digitales"}, {"en": "Verifiable on-chain records", "es": "Registros verificables en cadena"}, {"en": "Metal certificates", "es": "Certificados de metal"}]', 1, '{"en": "Diplomas stored on blockchain cannot be faked.", "es": "Diplomas almacenados en blockchain no pueden falsificarse."}'),
((SELECT id FROM s5), '{"en": "What is cross-border payments use case?", "es": "¿Cuál es el caso de uso de pagos transfronterizos?"}', '[{"en": "Sending money internationally in minutes", "es": "Enviar dinero internacionalmente en minutos"}, {"en": "Currency exchange", "es": "Cambio de divisas"}, {"en": "Bank transfers", "es": "Transferencias bancarias"}]', 0, '{"en": "Crypto enables fast, cheap international transfers.", "es": "Crypto permite transferencias internacionales rápidas y baratas."}'),
((SELECT id FROM s5), '{"en": "What is energy trading on blockchain?", "es": "¿Qué es comercio de energía en blockchain?"}', '[{"en": "Selling solar power to neighbors", "es": "Vender energía solar a vecinos"}, {"en": "Mining Bitcoin", "es": "Minar Bitcoin"}, {"en": "Power plants", "es": "Plantas de energía"}]', 0, '{"en": "P2P energy trading between homes with solar panels.", "es": "Comercio P2P de energía entre casas con paneles solares."}'),
((SELECT id FROM s5), '{"en": "How can blockchain help refugees?", "es": "¿Cómo puede blockchain ayudar a refugiados?"}', '[{"en": "Faster travel", "es": "Viajes más rápidos"}, {"en": "Digital identity when documents are lost", "es": "Identidad digital cuando se pierden documentos"}, {"en": "More food", "es": "Más comida"}]', 1, '{"en": "Blockchain provides identity even without physical documents.", "es": "Blockchain provee identidad incluso sin documentos físicos."}');

-- =============================================
-- SECTION 6: Benefits (15 questions)
-- =============================================
WITH s6 AS (SELECT id FROM course_sections WHERE slug = 'benefits' AND course_id = 'web3-basics' LIMIT 1)
INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
VALUES
((SELECT id FROM s6), '{"en": "What is data sovereignty?", "es": "¿Qué es soberanía de datos?"}', '[{"en": "Government controls data", "es": "Gobierno controla datos"}, {"en": "You control your own data", "es": "Tú controlas tus propios datos"}, {"en": "Companies share data", "es": "Empresas comparten datos"}]', 1, '{"en": "You decide who can access your personal information.", "es": "Tú decides quién puede acceder a tu información."}'),
((SELECT id FROM s6), '{"en": "What is censorship resistance?", "es": "¿Qué es resistencia a censura?"}', '[{"en": "Content cannot be blocked", "es": "Contenido no puede bloquearse"}, {"en": "Fast content", "es": "Contenido rápido"}, {"en": "Free content", "es": "Contenido gratis"}]', 0, '{"en": "On blockchain, content cannot be removed by third parties.", "es": "En blockchain, contenido no puede ser eliminado por terceros."}'),
((SELECT id FROM s6), '{"en": "How many unbanked people are there globally?", "es": "¿Cuántas personas no bancarizadas hay globalmente?"}', '[{"en": "170 million", "es": "170 millones"}, {"en": "1.7 billion", "es": "1.7 mil millones"}, {"en": "17 billion", "es": "17 mil millones"}]', 1, '{"en": "About 1.7 billion adults lack bank accounts.", "es": "Aproximadamente 1.7 mil millones de adultos no tienen cuentas bancarias."}'),
((SELECT id FROM s6), '{"en": "How can Web3 help financial inclusion?", "es": "¿Cómo puede Web3 ayudar a inclusión financiera?"}', '[{"en": "More bank branches", "es": "Más sucursales bancarias"}, {"en": "Banking with just a phone", "es": "Banca solo con un teléfono"}, {"en": "Lower taxes", "es": "Impuestos más bajos"}]', 1, '{"en": "Anyone with a smartphone can access DeFi.", "es": "Cualquiera con un smartphone puede acceder a DeFi."}'),
((SELECT id FROM s6), '{"en": "What new jobs does Web3 create?", "es": "¿Qué nuevos trabajos crea Web3?"}', '[{"en": "Factory workers", "es": "Trabajadores de fábrica"}, {"en": "Blockchain developers, NFT artists", "es": "Desarrolladores blockchain, artistas NFT"}, {"en": "Bank tellers", "es": "Cajeros de banco"}]', 1, '{"en": "Web3 creates entirely new career paths.", "es": "Web3 crea nuevas trayectorias profesionales."}'),
((SELECT id FROM s6), '{"en": "What is the salary range for blockchain developers?", "es": "¿Cuál es el rango salarial para desarrolladores blockchain?"}', '[{"en": "$50-80k", "es": "$50-80k"}, {"en": "$150-300k", "es": "$150-300k"}, {"en": "$500k+", "es": "$500k+"}]', 1, '{"en": "Blockchain developers are in high demand.", "es": "Los desarrolladores blockchain tienen alta demanda."}'),
((SELECT id FROM s6), '{"en": "What is a DAO community manager?", "es": "¿Qué es un community manager de DAO?"}', '[{"en": "Someone who manages decentralized community", "es": "Alguien que gestiona comunidad descentralizada"}, {"en": "A banker", "es": "Un banquero"}, {"en": "A lawyer", "es": "Un abogado"}]', 0, '{"en": "DAOs need people to manage their communities.", "es": "Las DAOs necesitan personas para gestionar sus comunidades."}'),
((SELECT id FROM s6), '{"en": "Why is transparency a benefit?", "es": "¿Por qué la transparencia es un beneficio?"}', '[{"en": "Easier to hide things", "es": "Más fácil ocultar cosas"}, {"en": "Everyone can verify transactions", "es": "Todos pueden verificar transacciones"}, {"en": "Faster payments", "es": "Pagos más rápidos"}]', 1, '{"en": "Open ledgers mean no hidden corruption.", "es": "Libros abiertos significan sin corrupción oculta."}'),
((SELECT id FROM s6), '{"en": "What is permissionless access?", "es": "¿Qué es acceso sin permisos?"}', '[{"en": "Need approval to join", "es": "Necesitas aprobación para unirte"}, {"en": "Anyone can participate", "es": "Cualquiera puede participar"}, {"en": "Only invited members", "es": "Solo miembros invitados"}]', 1, '{"en": "No gatekeepers deciding who can use the system.", "es": "Sin guardianes decidiendo quién puede usar el sistema."}'),
((SELECT id FROM s6), '{"en": "How does Web3 reduce middlemen?", "es": "¿Cómo reduce Web3 los intermediarios?"}', '[{"en": "More regulations", "es": "Más regulaciones"}, {"en": "Direct peer-to-peer transactions", "es": "Transacciones directas peer-to-peer"}, {"en": "Bigger banks", "es": "Bancos más grandes"}]', 1, '{"en": "Transact directly without banks, brokers, or platforms.", "es": "Transacciona directamente sin bancos, brokers o plataformas."}'),
((SELECT id FROM s6), '{"en": "What is a Web3 investment opportunity?", "es": "¿Qué es una oportunidad de inversión Web3?"}', '[{"en": "Buying more stocks", "es": "Comprar más acciones"}, {"en": "Early access to tokens and protocols", "es": "Acceso temprano a tokens y protocolos"}, {"en": "Real estate only", "es": "Solo bienes raíces"}]', 1, '{"en": "Invest in new protocols and earn from growth.", "es": "Invierte en nuevos protocolos y gana del crecimiento."}'),
((SELECT id FROM s6), '{"en": "What is true digital ownership?", "es": "¿Qué es propiedad digital verdadera?"}', '[{"en": "Renting content", "es": "Alquilar contenido"}, {"en": "Owning assets that cannot be taken away", "es": "Poseer activos que no pueden quitarse"}, {"en": "Downloading files", "es": "Descargar archivos"}]', 1, '{"en": "NFTs and crypto are truly yours, not licensed.", "es": "Los NFTs y crypto son verdaderamente tuyos, no licenciados."}'),
((SELECT id FROM s6), '{"en": "How can creators benefit from Web3?", "es": "¿Cómo pueden los creadores beneficiarse de Web3?"}', '[{"en": "More followers", "es": "Más seguidores"}, {"en": "Direct monetization without platforms", "es": "Monetización directa sin plataformas"}, {"en": "Cheaper equipment", "es": "Equipo más barato"}]', 1, '{"en": "Sell directly to fans, keep most of the revenue.", "es": "Vende directamente a fans, quédate con casi todo el ingreso."}'),
((SELECT id FROM s6), '{"en": "What is interoperability in Web3?", "es": "¿Qué es interoperabilidad en Web3?"}', '[{"en": "One platform only", "es": "Solo una plataforma"}, {"en": "Assets work across different apps", "es": "Activos funcionan entre diferentes apps"}, {"en": "Private networks", "es": "Redes privadas"}]', 1, '{"en": "Your NFT from one game can be used in another.", "es": "Tu NFT de un juego puede usarse en otro."}'),
((SELECT id FROM s6), '{"en": "What is composability?", "es": "¿Qué es composabilidad?"}', '[{"en": "Breaking things apart", "es": "Separar cosas"}, {"en": "Building on top of existing protocols", "es": "Construir sobre protocolos existentes"}, {"en": "Starting from scratch", "es": "Empezar desde cero"}]', 1, '{"en": "DeFi protocols can be combined like legos.", "es": "Los protocolos DeFi pueden combinarse como legos."}');

-- =============================================
-- SECTION 7: Future (15 questions)
-- =============================================
WITH s7 AS (SELECT id FROM course_sections WHERE slug = 'future' AND course_id = 'web3-basics' LIMIT 1)
INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
VALUES
((SELECT id FROM s7), '{"en": "What is AI + Blockchain?", "es": "¿Qué es IA + Blockchain?"}', '[{"en": "Robots mining Bitcoin", "es": "Robots minando Bitcoin"}, {"en": "AI agents with their own wallets", "es": "Agentes IA con sus propias wallets"}, {"en": "Chatbots", "es": "Chatbots"}]', 1, '{"en": "AI agents will have autonomous economic activity.", "es": "Los agentes IA tendrán actividad económica autónoma."}'),
((SELECT id FROM s7), '{"en": "What are tokenized assets?", "es": "¿Qué son activos tokenizados?"}', '[{"en": "Game tokens", "es": "Tokens de juego"}, {"en": "Real assets as blockchain tokens", "es": "Activos reales como tokens blockchain"}, {"en": "Digital money", "es": "Dinero digital"}]', 1, '{"en": "Real estate, stocks, and art represented as tokens.", "es": "Inmuebles, acciones y arte representados como tokens."}'),
((SELECT id FROM s7), '{"en": "How much in tokenized assets by 2030?", "es": "¿Cuánto en activos tokenizados para 2030?"}', '[{"en": "$1 trillion", "es": "$1 billón"}, {"en": "$10+ trillion", "es": "$10+ billones"}, {"en": "$100 billion", "es": "$100 mil millones"}]', 1, '{"en": "Experts predict over $10 trillion in tokenized assets.", "es": "Expertos predicen más de $10 billones en activos tokenizados."}'),
((SELECT id FROM s7), '{"en": "What is mass adoption barrier?", "es": "¿Cuál es la barrera para adopción masiva?"}', '[{"en": "Too fast", "es": "Muy rápido"}, {"en": "Poor user experience", "es": "Mala experiencia de usuario"}, {"en": "Too cheap", "es": "Muy barato"}]', 1, '{"en": "Wallets are still too complex for average users.", "es": "Las wallets aún son muy complejas para usuarios promedio."}'),
((SELECT id FROM s7), '{"en": "What is account abstraction?", "es": "¿Qué es abstracción de cuentas?"}', '[{"en": "Abstract art NFTs", "es": "NFTs de arte abstracto"}, {"en": "Easier wallet experience", "es": "Experiencia de wallet más fácil"}, {"en": "Hidden accounts", "es": "Cuentas ocultas"}]', 1, '{"en": "Smart wallets that hide blockchain complexity.", "es": "Wallets inteligentes que ocultan la complejidad de blockchain."}'),
((SELECT id FROM s7), '{"en": "What are decentralized social networks?", "es": "¿Qué son redes sociales descentralizadas?"}', '[{"en": "Facebook but faster", "es": "Facebook pero más rápido"}, {"en": "Social media owned by users", "es": "Redes sociales propiedad de usuarios"}, {"en": "Private messaging", "es": "Mensajería privada"}]', 1, '{"en": "No company owns your data or content.", "es": "Ninguna empresa posee tus datos o contenido."}'),
((SELECT id FROM s7), '{"en": "What is Farcaster?", "es": "¿Qué es Farcaster?"}', '[{"en": "A spell from Harry Potter", "es": "Un hechizo de Harry Potter"}, {"en": "A decentralized social network", "es": "Una red social descentralizada"}, {"en": "A blockchain", "es": "Una blockchain"}]', 1, '{"en": "Farcaster is a decentralized social protocol.", "es": "Farcaster es un protocolo social descentralizado."}'),
((SELECT id FROM s7), '{"en": "What is Lens Protocol?", "es": "¿Qué es Lens Protocol?"}', '[{"en": "Camera app", "es": "App de cámara"}, {"en": "Decentralized social graph", "es": "Grafo social descentralizado"}, {"en": "Photo filter", "es": "Filtro de fotos"}]', 1, '{"en": "Lens lets you own your social connections.", "es": "Lens te permite poseer tus conexiones sociales."}'),
((SELECT id FROM s7), '{"en": "How many wallet users by 2030?", "es": "¿Cuántos usuarios de wallet para 2030?"}', '[{"en": "100 million", "es": "100 millones"}, {"en": "1 billion+", "es": "1 mil millones+"}, {"en": "10 million", "es": "10 millones"}]', 1, '{"en": "Predictions estimate over 1 billion wallet users.", "es": "Las predicciones estiman más de 1 mil millones de usuarios."}'),
((SELECT id FROM s7), '{"en": "What are CBDCs?", "es": "¿Qué son las CBDCs?"}', '[{"en": "Crypto coins", "es": "Monedas crypto"}, {"en": "Central Bank Digital Currencies", "es": "Monedas Digitales de Bancos Centrales"}, {"en": "Credit cards", "es": "Tarjetas de crédito"}]', 1, '{"en": "Government-issued digital currencies.", "es": "Monedas digitales emitidas por gobiernos."}'),
((SELECT id FROM s7), '{"en": "Will gaming use blockchain?", "es": "¿Usarán los juegos blockchain?"}', '[{"en": "Only a few", "es": "Solo algunos"}, {"en": "Most games will have blockchain economies", "es": "La mayoría de juegos tendrá economías blockchain"}, {"en": "None", "es": "Ninguno"}]', 1, '{"en": "Gaming is a major Web3 adoption driver.", "es": "Gaming es un gran impulsor de adopción de Web3."}'),
((SELECT id FROM s7), '{"en": "What is invisible blockchain?", "es": "¿Qué es blockchain invisible?"}', '[{"en": "Hidden transactions", "es": "Transacciones ocultas"}, {"en": "Users dont know theyre using blockchain", "es": "Usuarios no saben que usan blockchain"}, {"en": "Private blockchain", "es": "Blockchain privada"}]', 1, '{"en": "Best UX is when users dont notice the technology.", "es": "La mejor UX es cuando usuarios no notan la tecnología."}'),
((SELECT id FROM s7), '{"en": "What is onchain AI?", "es": "¿Qué es IA onchain?"}', '[{"en": "AI running on blockchain", "es": "IA corriendo en blockchain"}, {"en": "AI trading crypto", "es": "IA comerciando crypto"}, {"en": "AI art", "es": "Arte IA"}]', 0, '{"en": "AI models and agents that live on blockchain.", "es": "Modelos y agentes IA que viven en blockchain."}'),
((SELECT id FROM s7), '{"en": "Will Web3 replace Web2?", "es": "¿Web3 reemplazará a Web2?"}', '[{"en": "Completely", "es": "Completamente"}, {"en": "They will coexist and merge", "es": "Coexistirán y se fusionarán"}, {"en": "Never", "es": "Nunca"}]', 1, '{"en": "Web3 will integrate into existing web, not replace it.", "es": "Web3 se integrará en la web existente, no la reemplazará."}'),
((SELECT id FROM s7), '{"en": "What is the metaverse connection to Web3?", "es": "¿Cuál es la conexión del metaverso con Web3?"}', '[{"en": "No connection", "es": "Sin conexión"}, {"en": "Web3 enables true ownership in virtual worlds", "es": "Web3 permite propiedad real en mundos virtuales"}, {"en": "Same thing", "es": "Lo mismo"}]', 1, '{"en": "Own virtual land, items, and identity via blockchain.", "es": "Posee terreno virtual, items e identidad vía blockchain."}');

-- =============================================
-- SECTION 8: FAQs (15 questions)
-- =============================================
WITH s8 AS (SELECT id FROM course_sections WHERE slug = 'faqs' AND course_id = 'web3-basics' LIMIT 1)
INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
VALUES
((SELECT id FROM s8), '{"en": "Is Web3 the same as crypto?", "es": "¿Es Web3 lo mismo que crypto?"}', '[{"en": "Yes", "es": "Sí"}, {"en": "No, crypto is one part of Web3", "es": "No, crypto es una parte de Web3"}, {"en": "Completely different", "es": "Completamente diferente"}]', 1, '{"en": "Crypto is the financial layer; Web3 is the broader vision.", "es": "Crypto es la capa financiera; Web3 es la visión más amplia."}'),
((SELECT id FROM s8), '{"en": "Do you need coding to use Web3?", "es": "¿Necesitas programar para usar Web3?"}', '[{"en": "Yes, always", "es": "Sí, siempre"}, {"en": "No, just to build it", "es": "No, solo para construirlo"}, {"en": "Yes, for everything", "es": "Sí, para todo"}]', 1, '{"en": "You can use Web3 apps like any regular app.", "es": "Puedes usar apps Web3 como cualquier app normal."}'),
((SELECT id FROM s8), '{"en": "What wallet is recommended for beginners?", "es": "¿Qué wallet se recomienda para principiantes?"}', '[{"en": "Ledger", "es": "Ledger"}, {"en": "MetaMask", "es": "MetaMask"}, {"en": "Paper wallet", "es": "Wallet de papel"}]', 1, '{"en": "MetaMask is free and works in your browser.", "es": "MetaMask es gratis y funciona en tu navegador."}'),
((SELECT id FROM s8), '{"en": "Can you lose money in crypto?", "es": "¿Puedes perder dinero en crypto?"}', '[{"en": "Never", "es": "Nunca"}, {"en": "Yes, if you invest irresponsibly", "es": "Sí, si inviertes irresponsablemente"}, {"en": "Only if hacked", "es": "Solo si te hackean"}]', 1, '{"en": "Crypto is volatile; never invest more than you can lose.", "es": "Crypto es volátil; nunca inviertas más de lo que puedes perder."}'),
((SELECT id FROM s8), '{"en": "Is it too late to start in Web3?", "es": "¿Es tarde para empezar en Web3?"}', '[{"en": "Yes, too late", "es": "Sí, muy tarde"}, {"en": "No, Web3 is still early", "es": "No, Web3 todavía está temprano"}, {"en": "Maybe", "es": "Quizás"}]', 1, '{"en": "Most people have not used Web3 yet. Still early.", "es": "La mayoría no ha usado Web3 aún. Todavía es temprano."}'),
((SELECT id FROM s8), '{"en": "Is Web3 safe?", "es": "¿Es Web3 seguro?"}', '[{"en": "Always safe", "es": "Siempre seguro"}, {"en": "Depends on how you use it", "es": "Depende de cómo lo uses"}, {"en": "Never safe", "es": "Nunca seguro"}]', 1, '{"en": "Learn security basics and start with small amounts.", "es": "Aprende seguridad básica y empieza con montos pequeños."}'),
((SELECT id FROM s8), '{"en": "What is a seed phrase?", "es": "¿Qué es una frase semilla?"}', '[{"en": "A password", "es": "Una contraseña"}, {"en": "12-24 words to recover your wallet", "es": "12-24 palabras para recuperar tu wallet"}, {"en": "Username", "es": "Nombre de usuario"}]', 1, '{"en": "Never share your seed phrase with anyone.", "es": "Nunca compartas tu frase semilla con nadie."}'),
((SELECT id FROM s8), '{"en": "Who should you share your seed phrase with?", "es": "¿Con quién debes compartir tu frase semilla?"}', '[{"en": "Customer support", "es": "Soporte al cliente"}, {"en": "No one, ever", "es": "Nadie, nunca"}, {"en": "Family only", "es": "Solo familia"}]', 1, '{"en": "No legitimate service will ever ask for your seed phrase.", "es": "Ningún servicio legítimo pedirá tu frase semilla."}'),
((SELECT id FROM s8), '{"en": "What is gas?", "es": "¿Qué es gas?"}', '[{"en": "Fuel for cars", "es": "Combustible para autos"}, {"en": "Transaction fees on blockchain", "es": "Tarifas de transacción en blockchain"}, {"en": "Mining power", "es": "Poder de minería"}]', 1, '{"en": "Gas is paid to validators for processing transactions.", "es": "Gas se paga a validadores por procesar transacciones."}'),
((SELECT id FROM s8), '{"en": "Is this course financial advice?", "es": "¿Es este curso asesoría financiera?"}', '[{"en": "Yes", "es": "Sí"}, {"en": "No, it is educational only", "es": "No, es solo educativo"}, {"en": "Sometimes", "es": "A veces"}]', 1, '{"en": "Always do your own research before investing.", "es": "Siempre haz tu propia investigación antes de invertir."}'),
((SELECT id FROM s8), '{"en": "What is a hot wallet?", "es": "¿Qué es una hot wallet?"}', '[{"en": "Wallet connected to internet", "es": "Wallet conectada a internet"}, {"en": "Wallet in a safe", "es": "Wallet en una caja fuerte"}, {"en": "Paper wallet", "es": "Wallet de papel"}]', 0, '{"en": "Hot wallets are convenient but less secure.", "es": "Las hot wallets son convenientes pero menos seguras."}'),
((SELECT id FROM s8), '{"en": "What is a cold wallet?", "es": "¿Qué es una cold wallet?"}', '[{"en": "Frozen wallet", "es": "Wallet congelada"}, {"en": "Offline storage like Ledger", "es": "Almacenamiento offline como Ledger"}, {"en": "Old wallet", "es": "Wallet vieja"}]', 1, '{"en": "Cold wallets are offline and more secure.", "es": "Las cold wallets están offline y son más seguras."}'),
((SELECT id FROM s8), '{"en": "How do you buy your first crypto?", "es": "¿Cómo compras tu primer crypto?"}', '[{"en": "On the street", "es": "En la calle"}, {"en": "Through an exchange like Coinbase", "es": "A través de un exchange como Coinbase"}, {"en": "Mining only", "es": "Solo minando"}]', 1, '{"en": "Use a reputable exchange to start.", "es": "Usa un exchange de buena reputación para empezar."}'),
((SELECT id FROM s8), '{"en": "What is DYOR?", "es": "¿Qué es DYOR?"}', '[{"en": "Do Your Own Research", "es": "Haz Tu Propia Investigación"}, {"en": "Dont You Own Riches", "es": "No Posees Riquezas"}, {"en": "Daily Yield On Returns", "es": "Rendimiento Diario en Retornos"}]', 0, '{"en": "Always research before investing in any project.", "es": "Siempre investiga antes de invertir en cualquier proyecto."}'),
((SELECT id FROM s8), '{"en": "What is the best way to learn Web3?", "es": "¿Cuál es la mejor forma de aprender Web3?"}', '[{"en": "Only reading", "es": "Solo leer"}, {"en": "Learning by doing", "es": "Aprender haciendo"}, {"en": "Watching videos only", "es": "Solo ver videos"}]', 1, '{"en": "Get a wallet, try some apps, learn by experience.", "es": "Obtén una wallet, prueba apps, aprende con experiencia."}');
