-- =============================================
-- CRYPTO-101 QUIZ QUESTIONS - PART 2 (Sections 4-6)
-- 15 questions per section
-- =============================================

-- SECTION 4: Key Security Concepts (15 questions)
INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is a private key?", "es": "¿Qué es una clave privada?"}',
  '[{"en": "Your email address", "es": "Tu dirección de email"}, {"en": "A secret code that controls your crypto", "es": "Un código secreto que controla tu crypto"}, {"en": "Your username", "es": "Tu nombre de usuario"}, {"en": "A public address", "es": "Una dirección pública"}]',
  1,
  '{"en": "A private key is a secret cryptographic code that proves ownership of your crypto.", "es": "Una clave privada es un código criptográfico secreto que prueba propiedad de tu crypto."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Can you change your private key?", "es": "¿Puedes cambiar tu clave privada?"}',
  '[{"en": "Yes, anytime", "es": "Sí, en cualquier momento"}, {"en": "Yes, once per year", "es": "Sí, una vez al año"}, {"en": "No, never", "es": "No, nunca"}, {"en": "Only with bank approval", "es": "Solo con aprobación del banco"}]',
  2,
  '{"en": "Unlike passwords, private keys cannot be changed - guard them carefully.", "es": "A diferencia de las contraseñas, las claves privadas no pueden cambiarse - guárdalas cuidadosamente."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is a seed phrase?", "es": "¿Qué es una frase semilla?"}',
  '[{"en": "A password you create", "es": "Una contraseña que creas"}, {"en": "12-24 words that can recover your wallet", "es": "12-24 palabras que pueden recuperar tu wallet"}, {"en": "Your username", "es": "Tu nombre de usuario"}, {"en": "A type of cryptocurrency", "es": "Un tipo de criptomoneda"}]',
  1,
  '{"en": "A seed phrase is 12-24 words generated by your wallet that can recover all your accounts.", "es": "Una frase semilla son 12-24 palabras generadas por tu wallet que pueden recuperar todas tus cuentas."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "How should you store your seed phrase?", "es": "¿Cómo deberías guardar tu frase semilla?"}',
  '[{"en": "Screenshot on your phone", "es": "Captura de pantalla en tu teléfono"}, {"en": "Written on paper, stored safely", "es": "Escrita en papel, guardada segura"}, {"en": "In cloud storage", "es": "En almacenamiento en la nube"}, {"en": "Email to yourself", "es": "Email a ti mismo"}]',
  1,
  '{"en": "Write it on paper and store in a secure place - never digitally where it can be hacked.", "es": "Escríbela en papel y guárdala en un lugar seguro - nunca digitalmente donde puede ser hackeada."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Should you ever share your seed phrase?", "es": "¿Deberías alguna vez compartir tu frase semilla?"}',
  '[{"en": "Yes, with support staff", "es": "Sí, con personal de soporte"}, {"en": "Yes, with trusted friends", "es": "Sí, con amigos de confianza"}, {"en": "Never, with anyone", "es": "Nunca, con nadie"}, {"en": "Only with family", "es": "Solo con familia"}]',
  2,
  '{"en": "NEVER share your seed phrase - no legitimate service will ever ask for it.", "es": "NUNCA compartas tu frase semilla - ningún servicio legítimo jamás la pedirá."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is a public address safe for?", "es": "¿Para qué es segura una dirección pública?"}',
  '[{"en": "Nothing, keep it secret", "es": "Nada, mantenla secreta"}, {"en": "Sharing to receive cryptocurrency", "es": "Compartir para recibir criptomonedas"}, {"en": "Recovering your wallet", "es": "Recuperar tu wallet"}, {"en": "Logging in", "es": "Iniciar sesión"}]',
  1,
  '{"en": "Your public address is like an email address - safe to share for receiving funds.", "es": "Tu dirección pública es como una dirección de email - segura para compartir al recibir fondos."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What 2FA method is recommended for crypto accounts?", "es": "¿Qué método 2FA se recomienda para cuentas crypto?"}',
  '[{"en": "SMS text messages", "es": "Mensajes de texto SMS"}, {"en": "Authenticator apps like Google Auth", "es": "Apps de autenticación como Google Auth"}, {"en": "Email codes", "es": "Códigos por email"}, {"en": "No 2FA needed", "es": "No se necesita 2FA"}]',
  1,
  '{"en": "Authenticator apps are more secure than SMS, which can be SIM-swapped by hackers.", "es": "Apps de autenticación son más seguras que SMS, que pueden ser víctimas de SIM-swapping."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What happens if someone gets your seed phrase?", "es": "¿Qué pasa si alguien obtiene tu frase semilla?"}',
  '[{"en": "Nothing, its just words", "es": "Nada, son solo palabras"}, {"en": "They can steal all your crypto", "es": "Pueden robar todo tu crypto"}, {"en": "They can reset your password", "es": "Pueden resetear tu contraseña"}, {"en": "They get read-only access", "es": "Obtienen acceso solo lectura"}]',
  1,
  '{"en": "Anyone with your seed phrase has complete control of your wallet and can drain it.", "es": "Cualquiera con tu frase semilla tiene control completo de tu wallet y puede vaciarla."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is a common scam in crypto?", "es": "¿Cuál es una estafa común en crypto?"}',
  '[{"en": "High gas fees", "es": "Tarifas de gas altas"}, {"en": "Websites asking for your seed phrase", "es": "Sitios web pidiendo tu frase semilla"}, {"en": "Using MetaMask", "es": "Usar MetaMask"}, {"en": "Trading on Coinbase", "es": "Tradear en Coinbase"}]',
  1,
  '{"en": "Any website or person asking for your seed phrase is a scam - 100% of the time.", "es": "Cualquier sitio web o persona pidiendo tu frase semilla es una estafa - 100% de las veces."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Why is SMS 2FA not recommended?", "es": "¿Por qué no se recomienda 2FA por SMS?"}',
  '[{"en": "Its too fast", "es": "Es muy rápido"}, {"en": "SIM swapping attacks can intercept it", "es": "Ataques de SIM swapping pueden interceptarlo"}, {"en": "Its free", "es": "Es gratis"}, {"en": "Everyone uses it", "es": "Todos lo usan"}]',
  1,
  '{"en": "Hackers can port your phone number (SIM swap) and receive your SMS codes.", "es": "Los hackers pueden portar tu número de teléfono (SIM swap) y recibir tus códigos SMS."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is the golden rule of crypto security?", "es": "¿Cuál es la regla de oro de seguridad crypto?"}',
  '[{"en": "Trust everyone", "es": "Confía en todos"}, {"en": "Share your earnings", "es": "Comparte tus ganancias"}, {"en": "Never share your seed phrase", "es": "Nunca compartas tu frase semilla"}, {"en": "Use the same password everywhere", "es": "Usa la misma contraseña en todos lados"}]',
  2,
  '{"en": "The #1 rule: NEVER share your seed phrase with anyone, for any reason.", "es": "La regla #1: NUNCA compartas tu frase semilla con nadie, por ninguna razón."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Should you store seed phrase in cloud storage?", "es": "¿Deberías guardar la frase semilla en almacenamiento en la nube?"}',
  '[{"en": "Yes, for backup", "es": "Sí, para respaldo"}, {"en": "No, it can be hacked", "es": "No, puede ser hackeada"}, {"en": "Only encrypted", "es": "Solo encriptada"}, {"en": "Only Google Drive", "es": "Solo Google Drive"}]',
  1,
  '{"en": "Never store seed phrases digitally - cloud services can be hacked or breached.", "es": "Nunca guardes frases semilla digitalmente - los servicios en la nube pueden ser hackeados."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What should you do if a customer support agent asks for your seed phrase?", "es": "¿Qué deberías hacer si un agente de soporte te pide tu frase semilla?"}',
  '[{"en": "Provide it immediately", "es": "Proporcionarla inmediatamente"}, {"en": "Recognize its a scam and report it", "es": "Reconocer que es una estafa y reportarlo"}, {"en": "Ask for their manager", "es": "Pedir hablar con su gerente"}, {"en": "Give half of it", "es": "Dar la mitad"}]',
  1,
  '{"en": "NO legitimate support will ever ask for your seed phrase - its always a scam.", "es": "NINGÚN soporte legítimo jamás pedirá tu frase semilla - siempre es una estafa."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "How many words are typically in a seed phrase?", "es": "¿Cuántas palabras hay típicamente en una frase semilla?"}',
  '[{"en": "5-10 words", "es": "5-10 palabras"}, {"en": "12-24 words", "es": "12-24 palabras"}, {"en": "50-100 words", "es": "50-100 palabras"}, {"en": "Just 1 word", "es": "Solo 1 palabra"}]',
  1,
  '{"en": "Most wallets use 12-24 word seed phrases following the BIP39 standard.", "es": "La mayoría de wallets usan frases semilla de 12-24 palabras siguiendo el estándar BIP39."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Why is security so critical in crypto?", "es": "¿Por qué la seguridad es tan crítica en crypto?"}',
  '[{"en": "Its not that important", "es": "No es tan importante"}, {"en": "Transactions are irreversible and theres no customer support", "es": "Las transacciones son irreversibles y no hay soporte al cliente"}, {"en": "For fun", "es": "Por diversión"}, {"en": "Government requires it", "es": "El gobierno lo requiere"}]',
  1,
  '{"en": "Lost or stolen crypto is usually gone forever - theres no bank to reverse transactions.", "es": "Crypto perdido o robado usualmente se pierde para siempre - no hay banco para revertir transacciones."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'security';

-- SECTION 5: Recommended First Steps (15 questions)
INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What wallet should beginners install first?", "es": "¿Qué wallet deberían instalar primero los principiantes?"}',
  '[{"en": "A $200 hardware wallet", "es": "Una wallet de hardware de $200"}, {"en": "MetaMask (free)", "es": "MetaMask (gratis)"}, {"en": "Build your own", "es": "Construir la tuya propia"}, {"en": "Paper wallet only", "es": "Solo wallet de papel"}]',
  1,
  '{"en": "MetaMask is free, easy to use, and widely supported - perfect for beginners.", "es": "MetaMask es gratis, fácil de usar, y ampliamente soportada - perfecta para principiantes."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "How much should a beginner invest initially?", "es": "¿Cuánto debería invertir un principiante inicialmente?"}',
  '[{"en": "All savings", "es": "Todos los ahorros"}, {"en": "Small amount they can afford to lose ($20-50)", "es": "Cantidad pequeña que puedan perder ($20-50)"}, {"en": "Nothing ever", "es": "Nada nunca"}, {"en": "At least $10,000", "es": "Al menos $10,000"}]',
  1,
  '{"en": "Start small with amounts you can afford to lose completely while learning.", "es": "Empieza pequeño con cantidades que puedas perder completamente mientras aprendes."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What should you do with your seed phrase on Day 1?", "es": "¿Qué deberías hacer con tu frase semilla en el Día 1?"}',
  '[{"en": "Screenshot it", "es": "Hacerle captura de pantalla"}, {"en": "Write it on paper and store securely", "es": "Escribirla en papel y guardar segura"}, {"en": "Email to yourself", "es": "Enviártela por email"}, {"en": "Share with family", "es": "Compartir con familia"}]',
  1,
  '{"en": "Write your seed phrase on paper immediately and store it somewhere safe.", "es": "Escribe tu frase semilla en papel inmediatamente y guárdala en algún lugar seguro."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Which exchanges are good for beginners?", "es": "¿Qué exchanges son buenos para principiantes?"}',
  '[{"en": "Random ones from ads", "es": "Aleatorios de anuncios"}, {"en": "Coinbase, Kraken", "es": "Coinbase, Kraken"}, {"en": "Telegram groups", "es": "Grupos de Telegram"}, {"en": "Any exchange", "es": "Cualquier exchange"}]',
  1,
  '{"en": "Trusted, regulated exchanges like Coinbase and Kraken are recommended for beginners.", "es": "Exchanges confiables y regulados como Coinbase y Kraken se recomiendan para principiantes."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What should you practice with your first crypto purchase?", "es": "¿Qué deberías practicar con tu primera compra de crypto?"}',
  '[{"en": "Leveraged trading", "es": "Trading con apalancamiento"}, {"en": "Sending to your personal wallet", "es": "Enviar a tu wallet personal"}, {"en": "Day trading", "es": "Day trading"}, {"en": "Lending it all", "es": "Prestarlo todo"}]',
  1,
  '{"en": "Practice the basics: buy small, send to your wallet, learn how transactions work.", "es": "Practica lo básico: compra poco, envía a tu wallet, aprende cómo funcionan las transacciones."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is a dApp?", "es": "¿Qué es una dApp?"}',
  '[{"en": "A broken app", "es": "Una app rota"}, {"en": "A decentralized application", "es": "Una aplicación descentralizada"}, {"en": "A dating app", "es": "Una app de citas"}, {"en": "A development app", "es": "Una app de desarrollo"}]',
  1,
  '{"en": "dApps are decentralized applications that run on blockchain networks.", "es": "Las dApps son aplicaciones descentralizadas que corren en redes blockchain."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Why should beginners start with small amounts?", "es": "¿Por qué deberían empezar los principiantes con cantidades pequeñas?"}',
  '[{"en": "Theres a maximum limit", "es": "Hay un límite máximo"}, {"en": "To learn by doing without risking much", "es": "Para aprender haciendo sin arriesgar mucho"}, {"en": "Small is more profitable", "es": "Pequeño es más profitable"}, {"en": "Regulations require it", "es": "Las regulaciones lo requieren"}]',
  1,
  '{"en": "Learning with small amounts lets you make mistakes without devastating losses.", "es": "Aprender con cantidades pequeñas te permite cometer errores sin pérdidas devastadoras."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is a Pro Tip for beginners?", "es": "¿Cuál es un consejo Pro para principiantes?"}',
  '[{"en": "Trust everything you read", "es": "Confía en todo lo que lees"}, {"en": "Be skeptical of everything too good to be true", "es": "Sé escéptico de todo demasiado bueno para ser verdad"}, {"en": "Invest your emergency fund", "es": "Invierte tu fondo de emergencia"}, {"en": "Share your seed phrase for backup", "es": "Comparte tu frase semilla para respaldo"}]',
  1,
  '{"en": "If it sounds too good to be true in crypto, it almost always is a scam.", "es": "Si suena demasiado bueno para ser verdad en crypto, casi siempre es una estafa."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Where can you stay informed about crypto?", "es": "¿Dónde puedes mantenerte informado sobre crypto?"}',
  '[{"en": "Only TV news", "es": "Solo noticias de TV"}, {"en": "Discord and Twitter communities", "es": "Comunidades de Discord y Twitter"}, {"en": "Avoid all information", "es": "Evita toda información"}, {"en": "Only official bank channels", "es": "Solo canales oficiales de bancos"}]',
  1,
  '{"en": "Crypto communities on Discord and Twitter are great for staying updated.", "es": "Las comunidades crypto en Discord y Twitter son geniales para mantenerse actualizado."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is the recommended timeline for your first week in crypto?", "es": "¿Cuál es la línea de tiempo recomendada para tu primera semana en crypto?"}',
  '[{"en": "Day 1: invest everything", "es": "Día 1: invertir todo"}, {"en": "Days 1-2: wallet setup, Days 3-4: exchange account, Days 5-7: small purchase", "es": "Días 1-2: configurar wallet, Días 3-4: cuenta en exchange, Días 5-7: pequeña compra"}, {"en": "Do everything in 1 hour", "es": "Hacer todo en 1 hora"}, {"en": "Wait 6 months before anything", "es": "Esperar 6 meses antes de nada"}]',
  1,
  '{"en": "Take it slow: setup wallet, secure seed phrase, create exchange account, then practice with small amounts.", "es": "Ve despacio: configura wallet, asegura frase semilla, crea cuenta en exchange, luego practica con cantidades pequeñas."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What should happen after your first purchase?", "es": "¿Qué debería pasar después de tu primera compra?"}',
  '[{"en": "Leave it on exchange forever", "es": "Dejarlo en el exchange para siempre"}, {"en": "Practice transferring to your wallet", "es": "Practicar transfiriendo a tu wallet"}, {"en": "Immediately trade", "es": "Tradear inmediatamente"}, {"en": "Forget about it", "es": "Olvidarte de ello"}]',
  1,
  '{"en": "Practice sending to your personal wallet to learn how transfers work.", "es": "Practica enviando a tu wallet personal para aprender cómo funcionan las transferencias."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Can you afford to lose money in crypto?", "es": "¿Puedes permitirte perder dinero en crypto?"}',
  '[{"en": "Crypto never loses value", "es": "Crypto nunca pierde valor"}, {"en": "Only invest what you can afford to lose completely", "es": "Solo invierte lo que puedes perder completamente"}, {"en": "Use your rent money", "es": "Usa el dinero de tu alquiler"}, {"en": "Guaranteed returns", "es": "Retornos garantizados"}]',
  1,
  '{"en": "Crypto is volatile - never invest more than you can afford to lose entirely.", "es": "Crypto es volátil - nunca inviertas más de lo que puedas perder completamente."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is DYOR?", "es": "¿Qué es DYOR?"}',
  '[{"en": "Do Your Own Research", "es": "Do Your Own Research (Haz Tu Propia Investigación)"}, {"en": "Daily Yearly Optimal Returns", "es": "Daily Yearly Optimal Returns"}, {"en": "A cryptocurrency name", "es": "Un nombre de criptomoneda"}, {"en": "A wallet type", "es": "Un tipo de wallet"}]',
  0,
  '{"en": "DYOR = Do Your Own Research - verify everything before investing.", "es": "DYOR = Do Your Own Research (Haz Tu Propia Investigación) - verifica todo antes de invertir."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Why explore a dApp in your first week?", "es": "¿Por qué explorar una dApp en tu primera semana?"}',
  '[{"en": "Its mandatory", "es": "Es obligatorio"}, {"en": "To understand what Web3 can do", "es": "Para entender qué puede hacer Web3"}, {"en": "To make money", "es": "Para ganar dinero"}, {"en": "To sell NFTs", "es": "Para vender NFTs"}]',
  1,
  '{"en": "Exploring a dApp helps you understand the practical applications of Web3.", "es": "Explorar una dApp te ayuda a entender las aplicaciones prácticas de Web3."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What mindset is important for beginners?", "es": "¿Qué mentalidad es importante para principiantes?"}',
  '[{"en": "Get rich quick", "es": "Hacerse rico rápido"}, {"en": "Learn before earning", "es": "Aprender antes de ganar"}, {"en": "Trust everyone", "es": "Confiar en todos"}, {"en": "Fear everything", "es": "Temer todo"}]',
  1,
  '{"en": "Focus on learning and understanding before trying to make profits.", "es": "Enfócate en aprender y entender antes de intentar obtener ganancias."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'first-steps';

-- SECTION 6: How to Buy Crypto (15 questions)
INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is a cryptocurrency exchange?", "es": "¿Qué es un exchange de criptomonedas?"}',
  '[{"en": "A physical store", "es": "Una tienda física"}, {"en": "A platform to buy and sell crypto", "es": "Una plataforma para comprar y vender crypto"}, {"en": "A type of wallet", "es": "Un tipo de wallet"}, {"en": "A blockchain", "es": "Un blockchain"}]',
  1,
  '{"en": "Exchanges are platforms where you can buy, sell, and trade cryptocurrencies.", "es": "Los exchanges son plataformas donde puedes comprar, vender, y tradear criptomonedas."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Which exchange is known for being beginner-friendly?", "es": "¿Qué exchange es conocido por ser amigable para principiantes?"}',
  '[{"en": "Binance", "es": "Binance"}, {"en": "Coinbase", "es": "Coinbase"}, {"en": "Uniswap", "es": "Uniswap"}, {"en": "PancakeSwap", "es": "PancakeSwap"}]',
  1,
  '{"en": "Coinbase is known for its simple interface, making it great for beginners.", "es": "Coinbase es conocido por su interfaz simple, haciéndolo genial para principiantes."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is a maker fee?", "es": "¿Qué es una tarifa maker?"}',
  '[{"en": "Fee for taking liquidity", "es": "Tarifa por tomar liquidez"}, {"en": "Fee for adding liquidity to the order book", "es": "Tarifa por añadir liquidez al libro de órdenes"}, {"en": "Fee for withdrawals", "es": "Tarifa por retiros"}, {"en": "No fees", "es": "Sin tarifas"}]',
  1,
  '{"en": "Maker fees apply when you add liquidity by placing limit orders.", "es": "Las tarifas maker aplican cuando añades liquidez colocando órdenes límite."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is a taker fee?", "es": "¿Qué es una tarifa taker?"}',
  '[{"en": "Fee for adding liquidity", "es": "Tarifa por añadir liquidez"}, {"en": "Fee for taking liquidity from the order book", "es": "Tarifa por tomar liquidez del libro de órdenes"}, {"en": "Monthly subscription", "es": "Suscripción mensual"}, {"en": "Free trading", "es": "Trading gratuito"}]',
  1,
  '{"en": "Taker fees apply when you remove liquidity with market orders.", "es": "Las tarifas taker aplican cuando remueves liquidez con órdenes de mercado."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Which exchange typically has the lowest fees?", "es": "¿Qué exchange típicamente tiene las tarifas más bajas?"}',
  '[{"en": "Coinbase", "es": "Coinbase"}, {"en": "Crypto.com", "es": "Crypto.com"}, {"en": "Binance", "es": "Binance"}, {"en": "Robinhood", "es": "Robinhood"}]',
  2,
  '{"en": "Binance is known for having some of the lowest trading fees in the industry.", "es": "Binance es conocido por tener algunas de las tarifas de trading más bajas de la industria."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is spread in crypto trading?", "es": "¿Qué es el spread en trading crypto?"}',
  '[{"en": "A type of cryptocurrency", "es": "Un tipo de criptomoneda"}, {"en": "Hidden fee in price difference", "es": "Tarifa oculta en diferencia de precio"}, {"en": "A trading strategy", "es": "Una estrategia de trading"}, {"en": "Exchange name", "es": "Nombre de exchange"}]',
  1,
  '{"en": "Spread is the difference between buy and sell prices - a hidden cost in trading.", "es": "El spread es la diferencia entre precios de compra y venta - un costo oculto en trading."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is a withdrawal fee?", "es": "¿Qué es una tarifa de retiro?"}',
  '[{"en": "Fee to create an account", "es": "Tarifa para crear cuenta"}, {"en": "Cost to send crypto to your wallet", "es": "Costo de enviar crypto a tu wallet"}, {"en": "Fee to buy crypto", "es": "Tarifa para comprar crypto"}, {"en": "Monthly maintenance fee", "es": "Tarifa de mantenimiento mensual"}]',
  1,
  '{"en": "Withdrawal fees are charged when you send crypto from the exchange to your wallet.", "es": "Las tarifas de retiro se cobran cuando envías crypto del exchange a tu wallet."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is Kraken known for?", "es": "¿Por qué es conocido Kraken?"}',
  '[{"en": "Highest fees", "es": "Tarifas más altas"}, {"en": "Lower fees and good security", "es": "Tarifas más bajas y buena seguridad"}, {"en": "Only Bitcoin", "es": "Solo Bitcoin"}, {"en": "Mobile only", "es": "Solo móvil"}]',
  1,
  '{"en": "Kraken is known for competitive fees, strong security, and reliable service.", "es": "Kraken es conocido por tarifas competitivas, fuerte seguridad, y servicio confiable."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Why might Binance be complex for beginners?", "es": "¿Por qué podría Binance ser complejo para principiantes?"}',
  '[{"en": "It has no features", "es": "No tiene características"}, {"en": "Too many options and trading pairs", "es": "Demasiadas opciones y pares de trading"}, {"en": "Its only in Chinese", "es": "Solo está en chino"}, {"en": "Requires $1000 minimum", "es": "Requiere $1000 mínimo"}]',
  1,
  '{"en": "Binance offers many advanced features that can overwhelm new users.", "es": "Binance ofrece muchas características avanzadas que pueden abrumar a nuevos usuarios."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is Crypto.com known for?", "es": "¿Por qué es conocido Crypto.com?"}',
  '[{"en": "Being the oldest", "es": "Ser el más antiguo"}, {"en": "Card rewards and mobile-first experience", "es": "Recompensas de tarjeta y experiencia mobile-first"}, {"en": "Only desktop", "es": "Solo escritorio"}, {"en": "No app available", "es": "Sin app disponible"}]',
  1,
  '{"en": "Crypto.com offers a Visa card with crypto rewards and a great mobile app.", "es": "Crypto.com ofrece una tarjeta Visa con recompensas crypto y una gran app móvil."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What documents are typically needed to sign up for an exchange?", "es": "¿Qué documentos se necesitan típicamente para registrarse en un exchange?"}',
  '[{"en": "Nothing, anonymous signup", "es": "Nada, registro anónimo"}, {"en": "ID and proof of address (KYC)", "es": "ID y prueba de domicilio (KYC)"}, {"en": "Only email", "es": "Solo email"}, {"en": "Bitcoin private key", "es": "Clave privada de Bitcoin"}]',
  1,
  '{"en": "Most regulated exchanges require KYC (Know Your Customer) with ID verification.", "es": "La mayoría de exchanges regulados requieren KYC (Know Your Customer) con verificación de ID."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What is typical maker fee range?", "es": "¿Cuál es el rango típico de tarifa maker?"}',
  '[{"en": "0.1-0.5%", "es": "0.1-0.5%"}, {"en": "5-10%", "es": "5-10%"}, {"en": "50-100%", "es": "50-100%"}, {"en": "No fee", "es": "Sin tarifa"}]',
  0,
  '{"en": "Maker fees typically range from 0.1% to 0.5% depending on the exchange.", "es": "Las tarifas maker típicamente van de 0.1% a 0.5% dependiendo del exchange."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What should you compare when choosing an exchange?", "es": "¿Qué deberías comparar al elegir un exchange?"}',
  '[{"en": "Only the logo", "es": "Solo el logo"}, {"en": "Fees, security, coins available, user interface", "es": "Tarifas, seguridad, monedas disponibles, interfaz de usuario"}, {"en": "Nothing, all are the same", "es": "Nada, todos son iguales"}, {"en": "Office location only", "es": "Solo ubicación de oficina"}]',
  1,
  '{"en": "Compare fees, security track record, available cryptocurrencies, and ease of use.", "es": "Compara tarifas, historial de seguridad, criptomonedas disponibles, y facilidad de uso."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "Can you buy partial Bitcoin?", "es": "¿Puedes comprar Bitcoin parcial?"}',
  '[{"en": "No, must buy whole coins", "es": "No, debes comprar monedas enteras"}, {"en": "Yes, in fractions called satoshis", "es": "Sí, en fracciones llamadas satoshis"}, {"en": "Only on some exchanges", "es": "Solo en algunos exchanges"}, {"en": "Requires special permission", "es": "Requiere permiso especial"}]',
  1,
  '{"en": "You can buy any fraction of Bitcoin - even $1 worth. The smallest unit is a satoshi.", "es": "Puedes comprar cualquier fracción de Bitcoin - incluso $1. La unidad más pequeña es un satoshi."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';

INSERT INTO quiz_questions (section_id, question, options, correct_answer, explanation)
SELECT id,
  '{"en": "What payment methods do exchanges typically accept?", "es": "¿Qué métodos de pago aceptan típicamente los exchanges?"}',
  '[{"en": "Cash only", "es": "Solo efectivo"}, {"en": "Bank transfer, debit/credit cards", "es": "Transferencia bancaria, tarjetas de débito/crédito"}, {"en": "Cryptocurrency only", "es": "Solo criptomonedas"}, {"en": "Gift cards only", "es": "Solo tarjetas de regalo"}]',
  1,
  '{"en": "Most exchanges accept bank transfers, debit cards, and credit cards for purchases.", "es": "La mayoría de exchanges aceptan transferencias bancarias, tarjetas de débito, y tarjetas de crédito."}'
FROM course_sections WHERE course_id = 'crypto-101' AND slug = 'exchanges';
