-- =============================================
-- BALANCED QUIZ QUESTIONS - Improved Version
-- All options have similar length, correct_index varies (0-3)
-- Run this AFTER deleting existing game_questions or use ON CONFLICT
-- =============================================

-- First, clear dependent tables to avoid foreign key violations
-- Order matters: delete references first, then the referenced table
DELETE FROM game_answers WHERE TRUE;
DELETE FROM game_question_history WHERE TRUE;
DELETE FROM game_questions WHERE TRUE;

INSERT INTO game_questions (category, difficulty, question_text, options, correct_index, explanation, from_course) VALUES

-- =============================================
-- 1. CRYPTO 101 (15 questions)
-- =============================================

('Crypto 101', 'easy', 
 '{"en": "Who created Bitcoin?", "es": "¿Quién creó Bitcoin?"}',
 '[{"en": "Vitalik Buterin", "es": "Vitalik Buterin"}, {"en": "Charles Hoskinson", "es": "Charles Hoskinson"}, {"en": "Satoshi Nakamoto", "es": "Satoshi Nakamoto"}, {"en": "Gavin Andresen", "es": "Gavin Andresen"}]',
 2,
 '{"en": "Bitcoin was created by the pseudonymous Satoshi Nakamoto in 2008.", "es": "Bitcoin fue creado por el seudónimo Satoshi Nakamoto en 2008."}',
 'crypto-101'),

('Crypto 101', 'easy',
 '{"en": "What is the maximum supply of Bitcoin?", "es": "¿Cuál es el suministro máximo de Bitcoin?"}',
 '[{"en": "21 million coins", "es": "21 millones de monedas"}, {"en": "18 million coins", "es": "18 millones de monedas"}, {"en": "50 million coins", "es": "50 millones de monedas"}, {"en": "100 million coins", "es": "100 millones de monedas"}]',
 0,
 '{"en": "Bitcoin has a hard cap of 21 million coins that will ever exist.", "es": "Bitcoin tiene un límite máximo de 21 millones de monedas."}',
 'crypto-101'),

('Crypto 101', 'easy',
 '{"en": "What is Ethereum best known for?", "es": "¿Por qué es más conocido Ethereum?"}',
 '[{"en": "Fast payment processing", "es": "Procesamiento rápido de pagos"}, {"en": "Being digital gold", "es": "Ser oro digital"}, {"en": "Anonymous transactions", "es": "Transacciones anónimas"}, {"en": "Smart contract platform", "es": "Plataforma de contratos inteligentes"}]',
 3,
 '{"en": "Ethereum is primarily known for enabling smart contracts and dApps.", "es": "Ethereum es conocido por habilitar contratos inteligentes y dApps."}',
 'crypto-101'),

('Crypto 101', 'easy',
 '{"en": "What is a stablecoin designed to do?", "es": "¿Para qué está diseñada una stablecoin?"}',
 '[{"en": "Maintain a stable value", "es": "Mantener un valor estable"}, {"en": "Generate high returns", "es": "Generar altos rendimientos"}, {"en": "Replace traditional banks", "es": "Reemplazar bancos tradicionales"}, {"en": "Enable anonymous trading", "es": "Permitir trading anónimo"}]',
 0,
 '{"en": "Stablecoins are designed to maintain stable value, usually pegged to USD.", "es": "Las stablecoins están diseñadas para mantener valor estable, usualmente vinculadas al USD."}',
 'crypto-101'),

('Crypto 101', 'easy',
 '{"en": "What is an altcoin?", "es": "¿Qué es una altcoin?"}',
 '[{"en": "A Bitcoin upgrade", "es": "Una mejora de Bitcoin"}, {"en": "Any crypto except Bitcoin", "es": "Cualquier crypto excepto Bitcoin"}, {"en": "A type of wallet", "es": "Un tipo de billetera"}, {"en": "A mining pool", "es": "Un pool de minería"}]',
 1,
 '{"en": "Altcoin refers to any cryptocurrency other than Bitcoin.", "es": "Altcoin se refiere a cualquier criptomoneda que no sea Bitcoin."}',
 'crypto-101'),

('Crypto 101', 'medium',
 '{"en": "What happens during Bitcoin halving?", "es": "¿Qué sucede durante el halving de Bitcoin?"}',
 '[{"en": "Transaction fees double", "es": "Las tarifas de transacción se duplican"}, {"en": "Network speed increases", "es": "La velocidad de la red aumenta"}, {"en": "Mining rewards are cut in half", "es": "Las recompensas de minería se reducen a la mitad"}, {"en": "Total supply is reduced", "es": "El suministro total se reduce"}]',
 2,
 '{"en": "Bitcoin halving cuts the block reward in half approximately every 4 years.", "es": "El halving de Bitcoin reduce la recompensa del bloque a la mitad cada ~4 años."}',
 'crypto-101'),

('Crypto 101', 'medium',
 '{"en": "How is market cap calculated?", "es": "¿Cómo se calcula la capitalización de mercado?"}',
 '[{"en": "Trading volume times price", "es": "Volumen de trading por precio"}, {"en": "Price times circulating supply", "es": "Precio por suministro circulante"}, {"en": "Total supply times holders", "es": "Suministro total por poseedores"}, {"en": "Maximum supply times price", "es": "Suministro máximo por precio"}]',
 1,
 '{"en": "Market cap = current price × circulating supply.", "es": "Capitalización de mercado = precio actual × suministro circulante."}',
 'crypto-101'),

('Crypto 101', 'medium',
 '{"en": "What does HODL mean in crypto?", "es": "¿Qué significa HODL en crypto?"}',
 '[{"en": "A type of trading bot", "es": "Un tipo de bot de trading"}, {"en": "A blockchain protocol", "es": "Un protocolo blockchain"}, {"en": "Hold through volatility", "es": "Mantener durante la volatilidad"}, {"en": "A mining technique", "es": "Una técnica de minería"}]',
 2,
 '{"en": "HODL means holding your crypto through market volatility.", "es": "HODL significa mantener tu crypto durante la volatilidad del mercado."}',
 'crypto-101'),

('Crypto 101', 'medium',
 '{"en": "What is a token burn?", "es": "¿Qué es una quema de tokens?"}',
 '[{"en": "Removing tokens permanently", "es": "Eliminar tokens permanentemente"}, {"en": "Creating new tokens", "es": "Crear nuevos tokens"}, {"en": "Transferring to cold storage", "es": "Transferir a almacenamiento frío"}, {"en": "Staking for rewards", "es": "Apostar por recompensas"}]',
 0,
 '{"en": "Token burning permanently removes tokens from circulation.", "es": "La quema de tokens elimina permanentemente tokens de circulación."}',
 'crypto-101'),

('Crypto 101', 'medium',
 '{"en": "What is a CEX?", "es": "¿Qué es un CEX?"}',
 '[{"en": "A decentralized exchange", "es": "Un exchange descentralizado"}, {"en": "A cryptocurrency wallet", "es": "Una billetera de criptomonedas"}, {"en": "A blockchain network", "es": "Una red blockchain"}, {"en": "A centralized exchange", "es": "Un exchange centralizado"}]',
 3,
 '{"en": "CEX (Centralized Exchange) is a trading platform like Coinbase or Binance.", "es": "CEX (Exchange Centralizado) es una plataforma como Coinbase o Binance."}',
 'crypto-101'),

('Crypto 101', 'hard',
 '{"en": "What distinguishes ERC-20 from ERC-721?", "es": "¿Qué distingue ERC-20 de ERC-721?"}',
 '[{"en": "ERC-20 is for Ethereum only", "es": "ERC-20 es solo para Ethereum"}, {"en": "ERC-721 tokens are unique", "es": "Los tokens ERC-721 son únicos"}, {"en": "ERC-20 is more expensive", "es": "ERC-20 es más costoso"}, {"en": "ERC-721 is much faster", "es": "ERC-721 es mucho más rápido"}]',
 1,
 '{"en": "ERC-20 tokens are fungible; ERC-721 tokens are non-fungible (NFTs).", "es": "Los tokens ERC-20 son fungibles; los ERC-721 son no fungibles (NFTs)."}',
 'crypto-101'),

('Crypto 101', 'hard',
 '{"en": "What is the UTXO model?", "es": "¿Qué es el modelo UTXO?"}',
 '[{"en": "Bitcoin''s accounting model", "es": "El modelo contable de Bitcoin"}, {"en": "Ethereum''s gas system", "es": "El sistema de gas de Ethereum"}, {"en": "A consensus mechanism", "es": "Un mecanismo de consenso"}, {"en": "A wallet standard", "es": "Un estándar de billetera"}]',
 0,
 '{"en": "UTXO (Unspent Transaction Output) is Bitcoin''s accounting model.", "es": "UTXO (Salida de Transacción No Gastada) es el modelo contable de Bitcoin."}',
 'crypto-101'),

('Crypto 101', 'hard',
 '{"en": "What is a hard fork?", "es": "¿Qué es un hard fork?"}',
 '[{"en": "A wallet backup method", "es": "Un método de respaldo de billetera"}, {"en": "A mining pool feature", "es": "Una característica de pool de minería"}, {"en": "A price correction event", "es": "Un evento de corrección de precio"}, {"en": "A permanent chain split", "es": "Una división permanente de cadena"}]',
 3,
 '{"en": "A hard fork permanently splits a blockchain into two separate chains.", "es": "Un hard fork divide permanentemente una blockchain en dos cadenas separadas."}',
 'crypto-101'),

('Crypto 101', 'hard',
 '{"en": "How does Proof of Stake work?", "es": "¿Cómo funciona Proof of Stake?"}',
 '[{"en": "Miners solve complex puzzles", "es": "Los mineros resuelven puzzles complejos"}, {"en": "Validators stake tokens as collateral", "es": "Los validadores apuestan tokens como colateral"}, {"en": "Nodes vote on transactions", "es": "Los nodos votan en transacciones"}, {"en": "Users pay for inclusion", "es": "Los usuarios pagan por inclusión"}]',
 1,
 '{"en": "In PoS, validators stake tokens as collateral to validate transactions.", "es": "En PoS, los validadores apuestan tokens como colateral para validar."}',
 'crypto-101'),

('Crypto 101', 'hard',
 '{"en": "What is an atomic swap?", "es": "¿Qué es un intercambio atómico?"}',
 '[{"en": "A fast trading strategy", "es": "Una estrategia de trading rápida"}, {"en": "A type of NFT transfer", "es": "Un tipo de transferencia de NFT"}, {"en": "Cross-chain trustless exchange", "es": "Intercambio sin confianza entre cadenas"}, {"en": "A wallet sync feature", "es": "Una función de sincronización de billetera"}]',
 2,
 '{"en": "Atomic swaps enable trustless exchanges between different blockchains.", "es": "Los swaps atómicos permiten intercambios sin confianza entre blockchains."}',
 'crypto-101'),

-- =============================================
-- 2. WEB3 BASICS (20 questions)
-- =============================================

('Web3 Basics', 'easy',
 '{"en": "What does Web3 primarily refer to?", "es": "¿A qué se refiere principalmente Web3?"}',
 '[{"en": "A new web browser version", "es": "Una nueva versión de navegador"}, {"en": "A social media platform", "es": "Una plataforma de redes sociales"}, {"en": "The decentralized internet", "es": "El internet descentralizado"}, {"en": "A programming framework", "es": "Un framework de programación"}]',
 2,
 '{"en": "Web3 refers to the decentralized internet powered by blockchain.", "es": "Web3 se refiere al internet descentralizado impulsado por blockchain."}',
 'web3-basics'),

('Web3 Basics', 'easy',
 '{"en": "In Web3, who controls your data?", "es": "En Web3, ¿quién controla tus datos?"}',
 '[{"en": "Large tech companies", "es": "Grandes empresas tecnológicas"}, {"en": "Government entities", "es": "Entidades gubernamentales"}, {"en": "Internet providers", "es": "Proveedores de internet"}, {"en": "You, the user", "es": "Tú, el usuario"}]',
 3,
 '{"en": "In Web3, users have ownership and control over their own data.", "es": "En Web3, los usuarios tienen propiedad y control sobre sus datos."}',
 'web3-basics'),

('Web3 Basics', 'easy',
 '{"en": "What is a blockchain?", "es": "¿Qué es una blockchain?"}',
 '[{"en": "A distributed ledger system", "es": "Un sistema de libro contable distribuido"}, {"en": "A type of cryptocurrency", "es": "Un tipo de criptomoneda"}, {"en": "A computer virus type", "es": "Un tipo de virus informático"}, {"en": "A social network app", "es": "Una app de red social"}]',
 0,
 '{"en": "A blockchain is a distributed ledger that records transactions immutably.", "es": "Una blockchain es un libro contable distribuido que registra transacciones."}',
 'web3-basics'),

('Web3 Basics', 'easy',
 '{"en": "What is a crypto wallet?", "es": "¿Qué es una billetera crypto?"}',
 '[{"en": "A physical money holder", "es": "Un contenedor físico de dinero"}, {"en": "A bank account type", "es": "Un tipo de cuenta bancaria"}, {"en": "Private key storage software", "es": "Software de almacenamiento de llaves privadas"}, {"en": "A credit card issuer", "es": "Un emisor de tarjetas de crédito"}]',
 2,
 '{"en": "A crypto wallet stores your private keys for managing cryptocurrencies.", "es": "Una billetera crypto almacena tus llaves privadas."}',
 'web3-basics'),

('Web3 Basics', 'easy',
 '{"en": "What differs Web2 from Web3?", "es": "¿Qué diferencia Web2 de Web3?"}',
 '[{"en": "Web3 is decentralized", "es": "Web3 es descentralizado"}, {"en": "Web3 loads faster", "es": "Web3 carga más rápido"}, {"en": "Web3 has more content", "es": "Web3 tiene más contenido"}, {"en": "Web3 uses less data", "es": "Web3 usa menos datos"}]',
 0,
 '{"en": "Web3 is decentralized; Web2 relies on centralized platforms.", "es": "Web3 es descentralizado; Web2 depende de plataformas centralizadas."}',
 'web3-basics'),

('Web3 Basics', 'easy',
 '{"en": "What is decentralization?", "es": "¿Qué es la descentralización?"}',
 '[{"en": "Central authority control", "es": "Control de autoridad central"}, {"en": "A fast internet type", "es": "Un tipo de internet rápido"}, {"en": "Distributed control model", "es": "Modelo de control distribuido"}, {"en": "A coding technique", "es": "Una técnica de programación"}]',
 2,
 '{"en": "Decentralization distributes control across many participants.", "es": "La descentralización distribuye el control entre muchos participantes."}',
 'web3-basics'),

('Web3 Basics', 'easy',
 '{"en": "What is a smart contract?", "es": "¿Qué es un contrato inteligente?"}',
 '[{"en": "A legal document online", "es": "Un documento legal en línea"}, {"en": "Self-executing blockchain code", "es": "Código auto-ejecutable en blockchain"}, {"en": "An AI legal assistant", "es": "Un asistente legal de IA"}, {"en": "A mobile banking app", "es": "Una app de banca móvil"}]',
 1,
 '{"en": "Smart contracts are self-executing code stored on a blockchain.", "es": "Los contratos inteligentes son código auto-ejecutable en blockchain."}',
 'web3-basics'),

('Web3 Basics', 'easy',
 '{"en": "What is a private key?", "es": "¿Qué es una llave privada?"}',
 '[{"en": "Your email password", "es": "Tu contraseña de email"}, {"en": "Your public username", "es": "Tu nombre de usuario público"}, {"en": "Secret crypto access code", "es": "Código secreto de acceso crypto"}, {"en": "A physical door key", "es": "Una llave física de puerta"}]',
 2,
 '{"en": "A private key is a secret code that gives access to your crypto.", "es": "Una llave privada es un código secreto de acceso a tu crypto."}',
 'web3-basics'),

('Web3 Basics', 'easy',
 '{"en": "What is a public key?", "es": "¿Qué es una llave pública?"}',
 '[{"en": "Your shareable address", "es": "Tu dirección compartible"}, {"en": "Your secret password", "es": "Tu contraseña secreta"}, {"en": "A government ID number", "es": "Un número de ID gubernamental"}, {"en": "A wallet backup code", "es": "Un código de respaldo de billetera"}]',
 0,
 '{"en": "A public key is your wallet address that others can see and send to.", "es": "Una llave pública es tu dirección de billetera visible para otros."}',
 'web3-basics'),

('Web3 Basics', 'easy',
 '{"en": "What is a dApp?", "es": "¿Qué es una dApp?"}',
 '[{"en": "A Google Play mobile app", "es": "Una app móvil de Google Play"}, {"en": "A desktop computer program", "es": "Un programa de computadora"}, {"en": "A decentralized application", "es": "Una aplicación descentralizada"}, {"en": "A web browser extension", "es": "Una extensión de navegador"}]',
 2,
 '{"en": "A dApp runs on blockchain rather than centralized servers.", "es": "Una dApp corre en blockchain en lugar de servidores centralizados."}',
 'web3-basics'),

('Web3 Basics', 'medium',
 '{"en": "What consensus does Bitcoin use?", "es": "¿Qué consenso usa Bitcoin?"}',
 '[{"en": "Proof of Stake (PoS)", "es": "Prueba de Participación (PoS)"}, {"en": "Delegated Proof of Stake", "es": "Prueba de Participación Delegada"}, {"en": "Proof of Authority", "es": "Prueba de Autoridad"}, {"en": "Proof of Work (PoW)", "es": "Prueba de Trabajo (PoW)"}]',
 3,
 '{"en": "Bitcoin uses Proof of Work where miners solve mathematical puzzles.", "es": "Bitcoin usa Prueba de Trabajo donde mineros resuelven puzzles."}',
 'web3-basics'),

('Web3 Basics', 'medium',
 '{"en": "What is gas in Ethereum?", "es": "¿Qué es el gas en Ethereum?"}',
 '[{"en": "Vehicle fuel type", "es": "Tipo de combustible vehicular"}, {"en": "Transaction processing fee", "es": "Tarifa de procesamiento de transacciones"}, {"en": "A token standard", "es": "Un estándar de token"}, {"en": "A mining reward type", "es": "Un tipo de recompensa de minería"}]',
 1,
 '{"en": "Gas is the fee paid to process transactions on Ethereum.", "es": "Gas es la tarifa pagada para procesar transacciones en Ethereum."}',
 'web3-basics'),

('Web3 Basics', 'medium',
 '{"en": "What is a seed phrase?", "es": "¿Qué es una frase semilla?"}',
 '[{"en": "A website password", "es": "Una contraseña de sitio web"}, {"en": "A cryptocurrency name", "es": "Un nombre de criptomoneda"}, {"en": "A user profile name", "es": "Un nombre de perfil de usuario"}, {"en": "Wallet recovery words", "es": "Palabras de recuperación de billetera"}]',
 3,
 '{"en": "A seed phrase is 12-24 words that can recover your wallet.", "es": "Una frase semilla son 12-24 palabras para recuperar tu billetera."}',
 'web3-basics'),

('Web3 Basics', 'medium',
 '{"en": "What is a DAO?", "es": "¿Qué es una DAO?"}',
 '[{"en": "Decentralized autonomous organization", "es": "Organización autónoma descentralizada"}, {"en": "A type of cryptocurrency token", "es": "Un tipo de token de criptomoneda"}, {"en": "A mining pool network", "es": "Una red de pool de minería"}, {"en": "A web browser extension", "es": "Una extensión de navegador web"}]',
 0,
 '{"en": "A DAO is an organization governed by smart contracts and voting.", "es": "Una DAO es una organización gobernada por contratos inteligentes."}',
 'web3-basics'),

('Web3 Basics', 'medium',
 '{"en": "What purpose does a hash serve?", "es": "¿Qué propósito sirve un hash?"}',
 '[{"en": "Encrypting private messages", "es": "Encriptar mensajes privados"}, {"en": "Mining new cryptocurrency", "es": "Minar nueva criptomoneda"}, {"en": "Creating data fingerprints", "es": "Crear huellas digitales de datos"}, {"en": "Sending email securely", "es": "Enviar email de forma segura"}]',
 2,
 '{"en": "A hash creates a unique fingerprint of data for verification.", "es": "Un hash crea una huella digital única de datos para verificación."}',
 'web3-basics'),

('Web3 Basics', 'medium',
 '{"en": "What is a blockchain node?", "es": "¿Qué es un nodo de blockchain?"}',
 '[{"en": "A type of token", "es": "Un tipo de token"}, {"en": "A computer running blockchain software", "es": "Una computadora ejecutando software blockchain"}, {"en": "A smart contract", "es": "Un contrato inteligente"}, {"en": "A wallet address", "es": "Una dirección de billetera"}]',
 1,
 '{"en": "A node is a computer that maintains the blockchain network.", "es": "Un nodo es una computadora que mantiene la red blockchain."}',
 'web3-basics'),

('Web3 Basics', 'medium',
 '{"en": "What does immutability mean?", "es": "¿Qué significa inmutabilidad?"}',
 '[{"en": "Data can be easily changed", "es": "Los datos pueden cambiarse fácilmente"}, {"en": "Data is stored encrypted", "es": "Los datos se almacenan encriptados"}, {"en": "Data is completely private", "es": "Los datos son completamente privados"}, {"en": "Data cannot be altered", "es": "Los datos no pueden alterarse"}]',
 3,
 '{"en": "Immutability means recorded data cannot be changed or deleted.", "es": "Inmutabilidad significa que los datos registrados no pueden alterarse."}',
 'web3-basics'),

('Web3 Basics', 'medium',
 '{"en": "What is Layer 2 in blockchain?", "es": "¿Qué es Capa 2 en blockchain?"}',
 '[{"en": "Scaling solution on top of Layer 1", "es": "Solución de escalado sobre Capa 1"}, {"en": "A slower backup network", "es": "Una red de respaldo más lenta"}, {"en": "The same as Layer 1", "es": "Lo mismo que Capa 1"}, {"en": "A type of wallet storage", "es": "Un tipo de almacenamiento de billetera"}]',
 0,
 '{"en": "Layer 2 solutions increase speed and reduce costs on Layer 1.", "es": "Las soluciones de Capa 2 aumentan velocidad y reducen costos."}',
 'web3-basics'),

('Web3 Basics', 'medium',
 '{"en": "What is an NFT?", "es": "¿Qué es un NFT?"}',
 '[{"en": "A fungible currency token", "es": "Un token de moneda fungible"}, {"en": "A blockchain network type", "es": "Un tipo de red blockchain"}, {"en": "A unique digital ownership token", "es": "Un token de propiedad digital único"}, {"en": "A wallet application type", "es": "Un tipo de aplicación de billetera"}]',
 2,
 '{"en": "An NFT is a unique token representing ownership of a specific item.", "es": "Un NFT es un token único que representa propiedad de un artículo."}',
 'web3-basics'),

('Web3 Basics', 'medium',
 '{"en": "What is DeFi?", "es": "¿Qué es DeFi?"}',
 '[{"en": "A social media platform", "es": "Una plataforma de redes sociales"}, {"en": "Decentralized financial services", "es": "Servicios financieros descentralizados"}, {"en": "A cryptocurrency exchange", "es": "Un exchange de criptomonedas"}, {"en": "A mining pool network", "es": "Una red de pool de minería"}]',
 1,
 '{"en": "DeFi refers to financial services built on blockchain.", "es": "DeFi se refiere a servicios financieros construidos en blockchain."}',
 'web3-basics'),

('Web3 Basics', 'hard',
 '{"en": "What is the Byzantine Generals Problem?", "es": "¿Qué es el Problema de los Generales Bizantinos?"}',
 '[{"en": "A historical military strategy", "es": "Una estrategia militar histórica"}, {"en": "Distributed consensus challenge", "es": "Desafío de consenso distribuido"}, {"en": "A cryptocurrency protocol", "es": "Un protocolo de criptomoneda"}, {"en": "A smart contract error", "es": "Un error de contrato inteligente"}]',
 1,
 '{"en": "It describes achieving consensus in distributed systems with faulty nodes.", "es": "Describe lograr consenso en sistemas distribuidos con nodos defectuosos."}',
 'web3-basics'),

('Web3 Basics', 'hard',
 '{"en": "What is a Merkle tree used for?", "es": "¿Para qué se usa un árbol Merkle?"}',
 '[{"en": "Storing cryptocurrency tokens", "es": "Almacenar tokens de criptomoneda"}, {"en": "Mining new blocks faster", "es": "Minar nuevos bloques más rápido"}, {"en": "Creating wallet addresses", "es": "Crear direcciones de billetera"}, {"en": "Efficient data verification", "es": "Verificación eficiente de datos"}]',
 3,
 '{"en": "Merkle trees efficiently verify data integrity in blockchains.", "es": "Los árboles Merkle verifican eficientemente la integridad de datos."}',
 'web3-basics'),

('Web3 Basics', 'hard',
 '{"en": "What is the blockchain trilemma?", "es": "¿Qué es el trilema de blockchain?"}',
 '[{"en": "Three cryptocurrency types", "es": "Tres tipos de criptomonedas"}, {"en": "Security, decentralization, scalability tradeoff", "es": "Equilibrio entre seguridad, descentralización, escalabilidad"}, {"en": "Three wallet options", "es": "Tres opciones de billetera"}, {"en": "Three mining methods", "es": "Tres métodos de minería"}]',
 1,
 '{"en": "The trilemma is the tradeoff between security, decentralization, and scalability.", "es": "El trilema es el equilibrio entre seguridad, descentralización y escalabilidad."}',
 'web3-basics'),

('Web3 Basics', 'hard',
 '{"en": "What is blockchain sharding?", "es": "¿Qué es el sharding de blockchain?"}',
 '[{"en": "Splitting chain for scalability", "es": "Dividir la cadena para escalabilidad"}, {"en": "A type of cryptocurrency", "es": "Un tipo de criptomoneda"}, {"en": "A wallet backup method", "es": "Un método de respaldo de billetera"}, {"en": "A mining technique", "es": "Una técnica de minería"}]',
 0,
 '{"en": "Sharding divides blockchain into pieces for parallel processing.", "es": "Sharding divide blockchain en piezas para procesamiento paralelo."}',
 'web3-basics'),

('Web3 Basics', 'hard',
 '{"en": "What is a 51% attack?", "es": "¿Qué es un ataque del 51%?"}',
 '[{"en": "Half of nodes going offline", "es": "La mitad de los nodos desconectándose"}, {"en": "A type of phishing scam", "es": "Un tipo de estafa de phishing"}, {"en": "A smart contract exploit", "es": "Un exploit de contrato inteligente"}, {"en": "Majority mining power control", "es": "Control mayoritario del poder de minería"}]',
 3,
 '{"en": "A 51% attack occurs when one entity controls majority mining power.", "es": "Un ataque del 51% ocurre cuando una entidad controla la mayoría del poder de minería."}',
 'web3-basics'),

('Web3 Basics', 'hard',
 '{"en": "What is a blockchain oracle?", "es": "¿Qué es un oráculo de blockchain?"}',
 '[{"en": "A fortune telling service", "es": "Un servicio de adivinación"}, {"en": "External data provider for smart contracts", "es": "Proveedor de datos externos para contratos inteligentes"}, {"en": "A type of wallet app", "es": "Un tipo de app de billetera"}, {"en": "A consensus mechanism", "es": "Un mecanismo de consenso"}]',
 1,
 '{"en": "Oracles bring external real-world data to smart contracts.", "es": "Los oráculos traen datos externos del mundo real a contratos inteligentes."}',
 'web3-basics'),

-- =============================================
-- 3. SECURITY (12 questions)
-- =============================================

('Security', 'easy',
 '{"en": "What should you NEVER share?", "es": "¿Qué NUNCA debes compartir?"}',
 '[{"en": "Your public wallet address", "es": "Tu dirección pública de billetera"}, {"en": "Your transaction history", "es": "Tu historial de transacciones"}, {"en": "Your seed phrase and private keys", "es": "Tu frase semilla y llaves privadas"}, {"en": "The cryptocurrencies you own", "es": "Las criptomonedas que posees"}]',
 2,
 '{"en": "Never share your seed phrase or private keys with anyone.", "es": "Nunca compartas tu frase semilla o llaves privadas."}',
 'safety'),

('Security', 'easy',
 '{"en": "What is phishing in crypto?", "es": "¿Qué es phishing en crypto?"}',
 '[{"en": "A type of cryptocurrency", "es": "Un tipo de criptomoneda"}, {"en": "Scam to steal sensitive info", "es": "Estafa para robar info sensible"}, {"en": "A mining technique", "es": "Una técnica de minería"}, {"en": "A trading strategy", "es": "Una estrategia de trading"}]',
 1,
 '{"en": "Phishing tricks you into revealing passwords or seed phrases.", "es": "Phishing te engaña para revelar contraseñas o frases semilla."}',
 'safety'),

('Security', 'easy',
 '{"en": "Where should you store your seed phrase?", "es": "¿Dónde debes guardar tu frase semilla?"}',
 '[{"en": "In your email inbox", "es": "En tu bandeja de correo"}, {"en": "In a computer text file", "es": "En un archivo de texto en computadora"}, {"en": "On social media privately", "es": "En redes sociales privadamente"}, {"en": "Written on paper securely stored", "es": "Escrita en papel guardada de forma segura"}]',
 3,
 '{"en": "Store your seed phrase on paper in a secure physical location.", "es": "Guarda tu frase semilla en papel en un lugar físico seguro."}',
 'safety'),

('Security', 'easy',
 '{"en": "What is a rug pull scam?", "es": "¿Qué es una estafa rug pull?"}',
 '[{"en": "A type of NFT artwork", "es": "Un tipo de arte NFT"}, {"en": "Developers abandoning with funds", "es": "Desarrolladores abandonando con fondos"}, {"en": "A trading strategy type", "es": "Un tipo de estrategia de trading"}, {"en": "A wallet backup method", "es": "Un método de respaldo de billetera"}]',
 1,
 '{"en": "Rug pulls occur when developers abandon a project with investor funds.", "es": "Los rug pulls ocurren cuando desarrolladores abandonan con fondos de inversores."}',
 'safety'),

('Security', 'easy',
 '{"en": "What is 2FA?", "es": "¿Qué es 2FA?"}',
 '[{"en": "A type of cryptocurrency", "es": "Un tipo de criptomoneda"}, {"en": "A trading platform name", "es": "Un nombre de plataforma de trading"}, {"en": "Two-Factor Authentication", "es": "Autenticación de Dos Factores"}, {"en": "A wallet type standard", "es": "Un estándar de tipo de billetera"}]',
 2,
 '{"en": "2FA adds an extra verification step for account security.", "es": "2FA añade un paso extra de verificación para seguridad de cuenta."}',
 'safety'),

('Security', 'medium',
 '{"en": "What is a hardware wallet?", "es": "¿Qué es una billetera hardware?"}',
 '[{"en": "A wallet app on phone", "es": "Una app de billetera en teléfono"}, {"en": "Physical offline key storage", "es": "Almacenamiento físico de llaves offline"}, {"en": "A type of cryptocurrency", "es": "Un tipo de criptomoneda"}, {"en": "A bank account service", "es": "Un servicio de cuenta bancaria"}]',
 1,
 '{"en": "Hardware wallets store private keys offline on physical devices.", "es": "Las billeteras hardware almacenan llaves privadas offline."}',
 'safety'),

('Security', 'medium',
 '{"en": "What is a honeypot scam?", "es": "¿Qué es una estafa honeypot?"}',
 '[{"en": "A type of staking reward", "es": "Un tipo de recompensa de staking"}, {"en": "A DeFi lending protocol", "es": "Un protocolo de préstamos DeFi"}, {"en": "Token that prevents selling", "es": "Token que previene vender"}, {"en": "A mining pool feature", "es": "Una característica de pool de minería"}]',
 2,
 '{"en": "Honeypots let you buy tokens but prevent you from selling them.", "es": "Los honeypots te dejan comprar tokens pero previenen venderlos."}',
 'safety'),

('Security', 'medium',
 '{"en": "What to check before connecting wallet?", "es": "¿Qué verificar antes de conectar billetera?"}',
 '[{"en": "The token current price", "es": "El precio actual del token"}, {"en": "URL and contract permissions", "es": "URL y permisos del contrato"}, {"en": "Number of other users", "es": "Número de otros usuarios"}, {"en": "The app color scheme", "es": "El esquema de colores de la app"}]',
 1,
 '{"en": "Always verify URL and review permissions before connecting.", "es": "Siempre verifica URL y revisa permisos antes de conectar."}',
 'safety'),

('Security', 'medium',
 '{"en": "What is token approval?", "es": "¿Qué es la aprobación de token?"}',
 '[{"en": "Getting listed on exchange", "es": "Ser listado en exchange"}, {"en": "Permission to spend tokens", "es": "Permiso para gastar tokens"}, {"en": "A type of airdrop reward", "es": "Un tipo de recompensa de airdrop"}, {"en": "A wallet backup feature", "es": "Una característica de respaldo de billetera"}]',
 1,
 '{"en": "Token approval lets a contract spend your tokens on your behalf.", "es": "La aprobación permite a un contrato gastar tus tokens."}',
 'safety'),

('Security', 'hard',
 '{"en": "What is a dusting attack?", "es": "¿Qué es un ataque de polvo?"}',
 '[{"en": "Sending large crypto amounts", "es": "Enviar grandes cantidades de crypto"}, {"en": "Sending tiny amounts to track wallets", "es": "Enviar cantidades diminutas para rastrear billeteras"}, {"en": "A mining pool attack", "es": "Un ataque a pool de minería"}, {"en": "A smart contract exploit", "es": "Un exploit de contrato inteligente"}]',
 1,
 '{"en": "Dusting sends tiny amounts to track and deanonymize wallet owners.", "es": "El dusting envía cantidades diminutas para rastrear y desanonimizar."}',
 'safety'),

('Security', 'hard',
 '{"en": "What is social engineering?", "es": "¿Qué es la ingeniería social?"}',
 '[{"en": "Building social platforms", "es": "Construir plataformas sociales"}, {"en": "A type of blockchain", "es": "Un tipo de blockchain"}, {"en": "Psychological manipulation tactics", "es": "Tácticas de manipulación psicológica"}, {"en": "A trading algorithm type", "es": "Un tipo de algoritmo de trading"}]',
 2,
 '{"en": "Social engineering manipulates people to reveal sensitive information.", "es": "La ingeniería social manipula personas para revelar información."}',
 'safety'),

('Security', 'hard',
 '{"en": "What is address poisoning?", "es": "¿Qué es el envenenamiento de direcciones?"}',
 '[{"en": "A type of staking method", "es": "Un tipo de método de staking"}, {"en": "Creating similar-looking addresses", "es": "Crear direcciones de aspecto similar"}, {"en": "A mining technique", "es": "Una técnica de minería"}, {"en": "A wallet backup feature", "es": "Una característica de respaldo de billetera"}]',
 1,
 '{"en": "Scammers create similar addresses hoping you copy the wrong one.", "es": "Estafadores crean direcciones similares esperando que copies la incorrecta."}',
 'safety'),

-- =============================================
-- 4. DEFI (12 questions)
-- =============================================

('DeFi', 'easy',
 '{"en": "What does DeFi stand for?", "es": "¿Qué significa DeFi?"}',
 '[{"en": "Digital Finance Services", "es": "Servicios de Finanzas Digitales"}, {"en": "Decentralized Finance", "es": "Finanzas Descentralizadas"}, {"en": "Derivative Finance Options", "es": "Opciones de Finanzas Derivadas"}, {"en": "Defined Finance Protocol", "es": "Protocolo de Finanzas Definidas"}]',
 1,
 '{"en": "DeFi stands for Decentralized Finance.", "es": "DeFi significa Finanzas Descentralizadas."}',
 'defi-deep-dive'),

('DeFi', 'easy',
 '{"en": "What is a DEX?", "es": "¿Qué es un DEX?"}',
 '[{"en": "A centralized exchange", "es": "Un exchange centralizado"}, {"en": "A digital wallet type", "es": "Un tipo de billetera digital"}, {"en": "A decentralized exchange", "es": "Un exchange descentralizado"}, {"en": "A mining pool network", "es": "Una red de pool de minería"}]',
 2,
 '{"en": "A DEX allows trading crypto without a central authority.", "es": "Un DEX permite intercambiar crypto sin autoridad central."}',
 'defi-deep-dive'),

('DeFi', 'easy',
 '{"en": "What is liquidity in DeFi?", "es": "¿Qué es la liquidez en DeFi?"}',
 '[{"en": "Physical water storage", "es": "Almacenamiento de agua física"}, {"en": "Available trading assets", "es": "Activos disponibles para trading"}, {"en": "A type of cryptocurrency", "es": "Un tipo de criptomoneda"}, {"en": "A wallet feature type", "es": "Un tipo de característica de billetera"}]',
 1,
 '{"en": "Liquidity is the availability of assets for trading in a pool.", "es": "Liquidez es la disponibilidad de activos para trading en un pool."}',
 'defi-deep-dive'),

('DeFi', 'easy',
 '{"en": "What is yield farming?", "es": "¿Qué es yield farming?"}',
 '[{"en": "Growing farm vegetables", "es": "Cultivar vegetales de granja"}, {"en": "Mining cryptocurrency tokens", "es": "Minar tokens de criptomoneda"}, {"en": "Day trading strategies", "es": "Estrategias de trading diario"}, {"en": "Earning rewards for liquidity", "es": "Ganar recompensas por liquidez"}]',
 3,
 '{"en": "Yield farming earns rewards by providing liquidity to protocols.", "es": "Yield farming gana recompensas proporcionando liquidez a protocolos."}',
 'defi-deep-dive'),

('DeFi', 'medium',
 '{"en": "What is an AMM?", "es": "¿Qué es un AMM?"}',
 '[{"en": "A type of cryptocurrency", "es": "Un tipo de criptomoneda"}, {"en": "Automated Market Maker", "es": "Creador de Mercado Automatizado"}, {"en": "A mining machine type", "es": "Un tipo de máquina de minería"}, {"en": "A wallet provider service", "es": "Un servicio de proveedor de billetera"}]',
 1,
 '{"en": "AMMs use algorithms for decentralized trading without order books.", "es": "Los AMM usan algoritmos para trading descentralizado sin libros de órdenes."}',
 'defi-deep-dive'),

('DeFi', 'medium',
 '{"en": "What is impermanent loss?", "es": "¿Qué es la pérdida impermanente?"}',
 '[{"en": "A permanent fund loss", "es": "Una pérdida permanente de fondos"}, {"en": "Loss from price changes in pools", "es": "Pérdida por cambios de precio en pools"}, {"en": "A trading fee charge", "es": "Un cargo de tarifa de trading"}, {"en": "A type of token standard", "es": "Un tipo de estándar de token"}]',
 1,
 '{"en": "Impermanent loss occurs when token prices change in a liquidity pool.", "es": "La pérdida impermanente ocurre cuando los precios cambian en un pool."}',
 'defi-deep-dive'),

('DeFi', 'medium',
 '{"en": "What is TVL in DeFi?", "es": "¿Qué es TVL en DeFi?"}',
 '[{"en": "Token Value Limit", "es": "Límite de Valor de Token"}, {"en": "Trading Volume Level", "es": "Nivel de Volumen de Trading"}, {"en": "Type of Virtual Ledger", "es": "Tipo de Libro Virtual"}, {"en": "Total Value Locked", "es": "Valor Total Bloqueado"}]',
 3,
 '{"en": "TVL measures total assets deposited in a DeFi protocol.", "es": "TVL mide los activos totales depositados en un protocolo DeFi."}',
 'defi-deep-dive'),

('DeFi', 'medium',
 '{"en": "What is collateral in DeFi?", "es": "¿Qué es el colateral en DeFi?"}',
 '[{"en": "A reward for lending", "es": "Una recompensa por prestar"}, {"en": "A type of stablecoin", "es": "Un tipo de stablecoin"}, {"en": "Assets locked to borrow", "es": "Activos bloqueados para pedir prestado"}, {"en": "A trading fee type", "es": "Un tipo de tarifa de trading"}]',
 2,
 '{"en": "Collateral is assets you lock to secure a loan.", "es": "Colateral son activos que bloqueas para asegurar un préstamo."}',
 'defi-deep-dive'),

('DeFi', 'hard',
 '{"en": "What is a liquidity pool?", "es": "¿Qué es un pool de liquidez?"}',
 '[{"en": "A swimming pool for traders", "es": "Una piscina para traders"}, {"en": "Paired tokens in a smart contract", "es": "Tokens pareados en un contrato inteligente"}, {"en": "A centralized exchange feature", "es": "Una característica de exchange centralizado"}, {"en": "A type of wallet storage", "es": "Un tipo de almacenamiento de billetera"}]',
 1,
 '{"en": "Liquidity pools hold token pairs for decentralized trading.", "es": "Los pools de liquidez mantienen pares de tokens para trading."}',
 'defi-deep-dive'),

('DeFi', 'hard',
 '{"en": "What is a vampire attack?", "es": "¿Qué es un ataque vampiro?"}',
 '[{"en": "A security exploit type", "es": "Un tipo de exploit de seguridad"}, {"en": "Incentivizing liquidity migration", "es": "Incentivar migración de liquidez"}, {"en": "A type of flash loan", "es": "Un tipo de préstamo flash"}, {"en": "A wallet hacking method", "es": "Un método de hackeo de billetera"}]',
 1,
 '{"en": "Vampire attacks offer incentives to drain competitor liquidity.", "es": "Los ataques vampiro ofrecen incentivos para drenar liquidez de competidores."}',
 'defi-deep-dive'),

('DeFi', 'hard',
 '{"en": "What is compound interest?", "es": "¿Qué es el interés compuesto?"}',
 '[{"en": "A faster interest type", "es": "Un tipo de interés más rápido"}, {"en": "Interest on accumulated interest", "es": "Interés sobre el interés acumulado"}, {"en": "The same as simple interest", "es": "Lo mismo que interés simple"}, {"en": "Interest only for NFTs", "es": "Interés solo para NFTs"}]',
 1,
 '{"en": "Compound interest earns returns on both principal and interest.", "es": "El interés compuesto gana sobre capital e interés acumulado."}',
 'defi-deep-dive'),

('DeFi', 'hard',
 '{"en": "What is a governance token?", "es": "¿Qué es un token de gobernanza?"}',
 '[{"en": "A type of stablecoin", "es": "Un tipo de stablecoin"}, {"en": "Token giving voting rights", "es": "Token que da derechos de voto"}, {"en": "A mining reward type", "es": "Un tipo de recompensa de minería"}, {"en": "A wallet address format", "es": "Un formato de dirección de billetera"}]',
 1,
 '{"en": "Governance tokens give holders voting rights in protocol decisions.", "es": "Los tokens de gobernanza dan derechos de voto en decisiones del protocolo."}',
 'defi-deep-dive'),

-- =============================================
-- 5. NFTs & ADVANCED (12 questions)
-- =============================================

('NFTs', 'easy',
 '{"en": "What does NFT stand for?", "es": "¿Qué significa NFT?"}',
 '[{"en": "New Financial Token", "es": "Nuevo Token Financiero"}, {"en": "Network File Transfer", "es": "Transferencia de Archivo de Red"}, {"en": "Non-Fungible Token", "es": "Token No Fungible"}, {"en": "Normal Finance Technology", "es": "Tecnología Financiera Normal"}]',
 2,
 '{"en": "NFT stands for Non-Fungible Token, meaning each is unique.", "es": "NFT significa Token No Fungible, cada uno es único."}',
 'nft-masterclass'),

('NFTs', 'easy',
 '{"en": "What makes NFTs different from Bitcoin?", "es": "¿Qué diferencia a los NFTs de Bitcoin?"}',
 '[{"en": "NFTs are more expensive", "es": "Los NFTs son más caros"}, {"en": "Each NFT is unique", "es": "Cada NFT es único"}, {"en": "NFTs are much faster", "es": "Los NFTs son mucho más rápidos"}, {"en": "NFTs do not use blockchain", "es": "Los NFTs no usan blockchain"}]',
 1,
 '{"en": "NFTs are non-fungible (unique); Bitcoin is fungible (interchangeable).", "es": "Los NFTs son no fungibles (únicos); Bitcoin es fungible."}',
 'nft-masterclass'),

('NFTs', 'easy',
 '{"en": "What can NFTs represent?", "es": "¿Qué pueden representar los NFTs?"}',
 '[{"en": "Only digital artwork", "es": "Solo arte digital"}, {"en": "Only physical items", "es": "Solo artículos físicos"}, {"en": "Only cryptocurrencies", "es": "Solo criptomonedas"}, {"en": "Art, music, games, and more", "es": "Arte, música, juegos y más"}]',
 3,
 '{"en": "NFTs can represent ownership of virtually anything digital or physical.", "es": "Los NFTs pueden representar propiedad de casi cualquier cosa."}',
 'nft-masterclass'),

('NFTs', 'medium',
 '{"en": "What is minting an NFT?", "es": "¿Qué es mintear un NFT?"}',
 '[{"en": "Buying an existing NFT", "es": "Comprar un NFT existente"}, {"en": "Selling your NFT collection", "es": "Vender tu colección de NFT"}, {"en": "Creating an NFT on blockchain", "es": "Crear un NFT en blockchain"}, {"en": "Burning an unwanted NFT", "es": "Quemar un NFT no deseado"}]',
 2,
 '{"en": "Minting creates and publishes a new NFT on the blockchain.", "es": "Mintear crea y publica un nuevo NFT en la blockchain."}',
 'nft-masterclass'),

('NFTs', 'medium',
 '{"en": "What are NFT royalties?", "es": "¿Qué son las regalías de NFT?"}',
 '[{"en": "A one-time payment only", "es": "Solo un pago único"}, {"en": "Creator earnings from resales", "es": "Ganancias del creador de reventas"}, {"en": "A type of NFT category", "es": "Un tipo de categoría de NFT"}, {"en": "A minting fee charge", "es": "Un cargo de tarifa de minteo"}]',
 1,
 '{"en": "Royalties let creators earn a percentage from secondary sales.", "es": "Las regalías permiten a creadores ganar porcentaje de reventas."}',
 'nft-masterclass'),

('NFTs', 'hard',
 '{"en": "What is a PFP NFT?", "es": "¿Qué es un PFP NFT?"}',
 '[{"en": "A physical NFT type", "es": "Un tipo de NFT físico"}, {"en": "Profile picture collection", "es": "Colección de fotos de perfil"}, {"en": "A payment method type", "es": "Un tipo de método de pago"}, {"en": "A wallet type standard", "es": "Un estándar de tipo de billetera"}]',
 1,
 '{"en": "PFP NFTs are designed to be used as social media profile pictures.", "es": "Los PFP NFTs están diseñados como fotos de perfil de redes sociales."}',
 'nft-masterclass'),

('Layer 2', 'medium',
 '{"en": "What is Layer 2 purpose?", "es": "¿Cuál es el propósito de Capa 2?"}',
 '[{"en": "To replace Layer 1 networks", "es": "Reemplazar redes de Capa 1"}, {"en": "To mine cryptocurrency faster", "es": "Minar criptomonedas más rápido"}, {"en": "To create new token types", "es": "Crear nuevos tipos de tokens"}, {"en": "Speed increase, cost reduction", "es": "Aumento de velocidad, reducción de costos"}]',
 3,
 '{"en": "Layer 2 increases speed and reduces costs while inheriting L1 security.", "es": "Capa 2 aumenta velocidad y reduce costos heredando seguridad de L1."}',
 NULL),

('Layer 2', 'medium',
 '{"en": "What is an optimistic rollup?", "es": "¿Qué es un rollup optimista?"}',
 '[{"en": "A fast trading strategy", "es": "Una estrategia de trading rápida"}, {"en": "L2 assuming transactions valid", "es": "L2 que asume transacciones válidas"}, {"en": "A type of wallet app", "es": "Un tipo de app de billetera"}, {"en": "A mining pool network", "es": "Una red de pool de minería"}]',
 1,
 '{"en": "Optimistic rollups assume transactions are valid unless challenged.", "es": "Los rollups optimistas asumen que las transacciones son válidas."}',
 NULL),

('Layer 2', 'hard',
 '{"en": "What is a ZK-rollup?", "es": "¿Qué es un ZK-rollup?"}',
 '[{"en": "A centralized exchange type", "es": "Un tipo de exchange centralizado"}, {"en": "Uses zero-knowledge proofs", "es": "Usa pruebas de conocimiento cero"}, {"en": "A stablecoin protocol", "es": "Un protocolo de stablecoin"}, {"en": "A wallet backup feature", "es": "Una característica de respaldo de billetera"}]',
 1,
 '{"en": "ZK-rollups use zero-knowledge proofs to verify transactions.", "es": "Los ZK-rollups usan pruebas de conocimiento cero para verificar."}',
 NULL),

('DAOs', 'medium',
 '{"en": "How do DAO members vote?", "es": "¿Cómo votan los miembros de una DAO?"}',
 '[{"en": "By email submission", "es": "Por envío de email"}, {"en": "By phone call voting", "es": "Por votación de llamada telefónica"}, {"en": "There is no voting process", "es": "No hay proceso de votación"}, {"en": "Using governance tokens", "es": "Usando tokens de gobernanza"}]',
 3,
 '{"en": "DAO members vote on proposals using governance tokens.", "es": "Los miembros de una DAO votan en propuestas usando tokens de gobernanza."}',
 NULL),

('DAOs', 'hard',
 '{"en": "What is a multisig wallet?", "es": "¿Qué es una billetera multisig?"}',
 '[{"en": "A wallet for multiple users", "es": "Una billetera para múltiples usuarios"}, {"en": "A type of hardware wallet", "es": "Un tipo de billetera hardware"}, {"en": "Requires multiple signatures", "es": "Requiere múltiples firmas"}, {"en": "A wallet just for NFTs", "es": "Una billetera solo para NFTs"}]',
 2,
 '{"en": "Multisig wallets require multiple signatures to authorize transactions.", "es": "Las billeteras multisig requieren múltiples firmas para autorizar."}',
 NULL),

('Tokenomics', 'medium',
 '{"en": "What is token vesting?", "es": "¿Qué es el vesting de tokens?"}',
 '[{"en": "Buying tokens quickly", "es": "Comprar tokens rápidamente"}, {"en": "Burning tokens permanently", "es": "Quemar tokens permanentemente"}, {"en": "Gradual token release schedule", "es": "Cronograma de liberación gradual de tokens"}, {"en": "Staking tokens for rewards", "es": "Apostar tokens por recompensas"}]',
 2,
 '{"en": "Vesting gradually releases tokens over time to align incentives.", "es": "El vesting libera tokens gradualmente para alinear incentivos."}',
 NULL)

ON CONFLICT DO NOTHING;
