-- Drop foreign key constraint on profiles.id if it exists
-- This allows us to create profiles with custom UUIDs generated by Privy sync
-- instead of relying on Supabase Auth user IDs.

DO $$ 
BEGIN 
  IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'profiles_id_fkey') THEN 
    ALTER TABLE profiles DROP CONSTRAINT profiles_id_fkey; 
  END IF; 
END $$;

-- Also verify if there are any other constraints linking to auth.users
-- Commonly "profiles_id_fkey" is the default for "references auth.users"
